### ISSUE TITLE
1.19.3 crashes

### ISSUE THREAD

**Issue by DiebderSeelen** [tr7zw/3d-Skin-Layers#103]
the new update, crashes the server, when it is starting..  
awesome mod, i hope it work soon

[crash-2023-03-21_03.39.29-fml.txt](https://github.com/tr7zw/3d-Skin-Layers/files/11034173/crash-2023-03-21_03.39.29-fml.txt)

**Comment by tr7zw** [comment]
Still not a server mod. Delete the jar and it will work. Will add the Forge-is-dumb failsafe sometime later.

**Comment by tr7zw** [comment]
This is a client mod. Putting it on a server at best does exactly nothing(like on fabric), and at worst crashes it(like on Forge). Just remove the jar from the server and that's it.
