### ISSUE TITLE
The 3d layers doesn't show in 1.19.3?

### ISSUE THREAD

**Issue by Ciel34** [tr7zw/3d-Skin-Layers#104]
![image](https://user-images.githubusercontent.com/129008389/227805021-b6447853-6981-47fb-8ab6-be29118104a3.png)

**Comment by tr7zw** [comment]
Wrong screenshot? Also make sure your skin actually has layers, that you are not using something like TLauncher, check that the mod shows up in the mod list ingame(ModMenu).

**Comment by Ciel34** [comment]
alright
