### ISSUE TITLE
Jacket layers clips with torso upon sneak

### ISSUE THREAD

**Issue by PancakeCultist** [tr7zw/3d-Skin-Layers#11]
whenever you sneak, the jacket layer seems to become displaced, and moves forward in relation to the torso, thus creating an issue where the torso clips through the jacket layer on the back.
![2021-09-24_12 04 56](https://user-images.githubusercontent.com/56564980/134715709-99494281-3c9b-46ed-b422-c21d75fd8076.png)
![2021-09-24_12 04 58](https://user-images.githubusercontent.com/56564980/134715726-e14f74a2-8703-4869-a89b-1b67f751242c.png)

**Comment by tr7zw** [comment]
I think the issue is that it's not moved(while sneaking the body moves back) and possibly custom setting values for the cube sizes?
