### ISSUE TITLE
Add lang\ru_ru.json

### ISSUE THREAD

**Issue by VGamerGroup** [tr7zw/3d-Skin-Layers#111]
I made a translation into Russian.

![image](https://github.com/tr7zw/3d-Skin-Layers/assets/109788628/5ee51495-b112-4665-8d99-9e4260fb20e1)

How can I transfer the Russian translation file to you?

My Discord tag: VGamerGroup#5048

**Comment by tr7zw** [comment]
You can directly pull request the file into the repo. If you have issues with that, you can post it to this issue or send it on the discord.

**Comment by VGamerGroup** [comment]
I have some problems there. Let me give you a file to discord?

**Comment by tr7zw** [comment]
The discord is linked on the mod page on modrinth and curseforge.

**Comment by tr7zw** [comment]
Pushed
