### ISSUE TITLE
Question/Issue: 3D layers work with TLaunder?

### ISSUE THREAD

**Issue by Nik1Ni** [tr7zw/3d-Skin-Layers#114]
Currently playing on 1.19.4 with TLauncher skins and it looks like the mod isn't working. 
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/138604360/1be0c160-56e2-45ce-8788-b997c84ed0e4)

**Comment by tr7zw** [comment]
No, it doesn't work with TLauncher. Buy the game, and it will work.

**Comment by Nik1Ni** [comment]
Strange, It worked perfectly on 1.12.2 with TLauncher but ok

**Comment by tr7zw** [comment]
I mean, then TLauncher had luck. I don't support piracy, and this bug is because TLauncher can't code correctly(and might contain malware).
