### ISSUE TITLE
MoreCulling issue w/ 3D Skin Layers

### ISSUE THREAD

**Issue by RisPNG** [tr7zw/3d-Skin-Layers#118]
I originally posted this on MoreCulling repository because I think it's easier for them to fix this incompatibility but I want to crosspost to this repository as well just to let you know.

Original Post: https://github.com/fxmorin/MoreCulling/issues/185#issue-1812930562

**Comment by tr7zw** [comment]
Hm weird, the solution has been posted over at the other issue. Going to keep this issue here for reference.

**Comment by RisPNG** [comment]
Fix by setting "entityModelCulling" to false in moreculling.toml in the config folder if you have Sodium installed. If you don't have Sodium installed, you should be able to toggle the option through the mod options in-game.
