### ISSUE TITLE
Crash when rendering heads

### ISSUE THREAD

**Issue by MATRIX-feather** [tr7zw/3d-Skin-Layers#123]
### Summary
The game crashes when rendering heads

#### Player heads:
1. Give yourself a player head with `/give @s player_head{SkullOwner:"Icalingua"}`
2. Crash

#### Other heads
1. Pick up a dragon head from creative inventory
2. Place it down
3. Crash

### Crash Logs
Player heads: https://pastebin.com/56R48ZDL
Other heads: https://pastebin.com/UqUMKqRx

**Comment by tr7zw** [comment]
The one time you don't give yourself a new head during testing, but just use the ones already in the inventory/placed 🙃
