### ISSUE TITLE
Error occurred with Emotecraft mod

### ISSUE THREAD

**Issue by Disguys** [tr7zw/3d-Skin-Layers#13]
I installed the Skin Layers 3D and Emotecraft mod on Fabric 1.17.1, apparently because of the 3D layer the hands cannot adjust to the animation, I do not know in which exactly the problem arises.
Video: https://youtu.be/sd2ydCt9ugo
Without Skin Layers, 3D animations works fine.

**Comment by tr7zw** [comment]
Yea these two together will basically not work. Don't think there is anything I can do about that, maaaaaybe the dev on Emotecraft can, if he has the time for that.

**Comment by tr7zw** [comment]
This was semi resolved. Depending on versions/releases it should work now.
