### ISSUE TITLE
Feature Request: Wildfires FGM Compatibility

### ISSUE THREAD

**Issue by LunarPidgeon** [tr7zw/3d-Skin-Layers#132]
Visually the two together look just fine, but theres issues with connecting to other players with the same combo. Connecting client gets kicked, host logs just report a regular disconnect message. Ive brought this up with the owner of FGM and basically got told "not my problem", which is why I'm bringing this here.  I honestly don't know why these two are having issues in multiplayer scenarios, other than that they obviously touch the player model. I tried to use figura instead, but couldnt get the result I wanted.
Anyway. It would be really nice if you could do some magic and fix the disconnecting issue. Could be easy could be impossible I dont know. Ill post the connecting client logs if I can find em. Thanks for your time.

**Comment by LunarPidgeon** [comment]
[Heres the link for what I posted on wildfires github.](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/issues/116) Its old but the disconnect message hasnt changed at all.

**Comment by tr7zw** [comment]
The crash linked on that other git is inside the network handler. This mod doesn't touch anything close to that, so it's 99% unrelated(added to that, there is nothing special about lan worlds).

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/3d-Skin-Layers/assets/5133936/eca94e5c-57d9-4f5d-8974-d75fe4b14be8)
