### ISSUE TITLE
help? 🥹

### ISSUE THREAD

**Issue by LXSHYZR** [tr7zw/3d-Skin-Layers#133]
The game crashed whilst rendering block entity Error: java.lang.NullPointerException: Cannot invoke "dev.tr7zw.skinlayers.api.Mesh.setPosition(float, float, float)" because "mesh" is null

**Comment by tr7zw** [comment]
If you are on 1.20.2, try this build https://github.com/tr7zw/3d-Skin-Layers/actions/runs/6907294082 (At the bottom the Artifacts button, then in the zip picking the Fabric/Forge folder depending on what you need and in the final folder the jar without -all or -sources at the end).

**Comment by LXSHYZR** [comment]
It worked!!!! thank you so much <333
