### ISSUE TITLE
Broken player model rendering with MineLittlePony pony player models.

### ISSUE THREAD

**Issue by NovaLynxie** [tr7zw/3d-Skin-Layers#136]
Hi there, I have noticed an unusual visual bug that affects pony player models with Mine Little Pony when 3D Skin Layers is installed.
When this mod is not installed, pony skins render properly.

Steps to reproduce:
1) Install the following mods with Fabric:
a) Mine Little Pony (and any dependencies it may need)
b) 3D Skin Layers
c) HD Skins (used to upload HD skins but is optional)
2) Use any pony skin uploaded to your account at Minecraft.net (or use HD skins here if installed)
3) Load into the game and go into F5 "third person".

As a pony player, it looks like this:
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/21307676/d55893ea-e026-4dcf-9cdb-13c45c056bd6)
It is worse with the "sea pony" player model as the "mane" or player's second head layer becomes detached and floats off the player's head.
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/21307676/652a8678-72a0-44d2-b22c-b663b29a69d6)

I don't know if this can be fixed or compatibility added, but I wanted to bring this to your attention since I already checked with the MineLittlePony mod community. They have said it's an incompatibility with this mod.

**Comment by tr7zw** [comment]
This mod is for the vanilla player model. No support from my end for that mod is planned.
