### ISSUE TITLE
[1.19.2] Endless error spam in logs on 1.6.0

### ISSUE THREAD

**Issue by Maypul** [tr7zw/3d-Skin-Layers#138]
After updating the mod to 1.6.0 and launching game, it throws endless errors in the log:
Looks like some mod conflicts that was not here on 1.5.2.

[errors.log](https://github.com/tr7zw/3d-Skin-Layers/files/13802066/errors.log)

**Comment by tr7zw** [comment]
entity_texture_features will need an update. Some stuff was renamed/merged this release, which breaks the etf's compat. Open an issue there.
