### ISSUE TITLE
Crashing when nothing in hand [FABRIC 1.20.4]

### ISSUE THREAD

**Issue by Betawolfy** [tr7zw/3d-Skin-Layers#139]
The mod works as expected, but when we choose a slot with nothing in it, the game crashes.

Loader: Fabric
Version: 1.20.4

Here is the error in the log:
`[12:17:00] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchFieldError: config
	at traben.entity_texture_features.compat.ETF3DSkinLayersUtil.renderHand(ETF3DSkinLayersUtil.java:28) ~[entity_texture_features_fabric_1.20.4-5.1.jar:?]
	at net.minecraft.class_1007.handler$zfn000$entity_texture_features$etf$redirectNicely(class_1007.java:577) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_23205(class_1007.java:195) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4220(class_1007.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3219(class_759.java:305) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3228(class_759.java:479) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_22976(class_759.java:396) ~[client-intermediary.jar:?]
	at net.coderbot.iris.pipeline.HandRenderer.renderSolid(HandRenderer.java:90) ~[iris-mc1.20.4-1.6.14.jar:?]
	at net.minecraft.class_761.handler$bdn000$iris$beginTranslucents(class_761.java:7400) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1267) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1098) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:866) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]`

here is the mod i used (in case there is a incompatibility):

`- appleskin 2.5.1+mc1.20.3
	- betterf3 9.0.0
	   \-- fabric-resource-loader-v0 0.11.15+78d798af4f
	- betterstats 3.7.1+fabric-1.20.4
	   \-- tcdcommons 3.7+fabric-1.20.4
	- bobby 5.0.3
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- bookshelf 23.0.1
	- chat_heads 0.10.27
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- craftpresence 2.2.6
	   \-- fabric-resource-loader-v0 0.11.15+78d798af4f
	- creativecore 2.11.16
	   \-- net_neoforged_bus 7.2.0
	- durabilitytooltip 1.1.5
	- enchdesc 20.0.1
	- enhancedvisuals 1.6.9
	- entity_model_features 1.2.1
	- entity_texture_features 5.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.3.1
	- fabric-api 0.92.0+1.20.4
	   |-- fabric-api-base 0.4.35+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.45+78d798af4f
	   |-- fabric-biome-api-v1 13.0.15+78d798af4f
	   |-- fabric-block-api-v1 1.0.14+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.3+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6+78d798af4f
	   |-- fabric-command-api-v1 1.2.40+f71b366f4f
	   |-- fabric-command-api-v2 2.2.19+78d798af4f
	   |-- fabric-commands-v0 0.2.57+df3654b34f
	   |-- fabric-containers-v0 0.1.81+df3654b34f
	   |-- fabric-content-registries-v0 5.0.9+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22+78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17+78d798af4f
	   |-- fabric-dimensions-v1 2.1.60+78d798af4f
	   |-- fabric-entity-events-v1 1.5.28+4ced05924f
	   |-- fabric-events-interaction-v0 0.7.0+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.71+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45+78d798af4f
	   |-- fabric-item-api-v1 2.1.34+78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40+78d798af4f
	   |-- fabric-keybindings-v0 0.2.38+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.29+78d798af4f
	   |-- fabric-loot-api-v2 2.1.4+78d798af4f
	   |-- fabric-message-api-v1 6.0.4+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7+78d798af4f
	   |-- fabric-models-v0 0.4.6+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.2+78d798af4f
	   |-- fabric-object-builder-api-v1 13.0.8+06274a474f
	   |-- fabric-particles-v1 1.1.6+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.13+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3+78d798af4f
	   |-- fabric-renderer-indigo 1.5.3+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.41+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.32+78d798af4f
	   |-- fabric-rendering-v0 1.1.53+df3654b34f
	   |-- fabric-rendering-v1 3.0.12+78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13+78d798af4f
	   |-- fabric-screen-api-v1 2.0.16+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50+78d798af4f
	   |-- fabric-sound-api-v1 1.0.16+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6+78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13+78d798af4f
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- ferritecore 6.0.3
	- forgeconfigapiport 20.4.0
	- indium 1.0.28+mc1.20.4
	- iris 1.6.14
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 13.2.1
	- java 17
	- kirin 1.17.0+1.20.4
	- lazydfu 0.1.3
	- lithium 0.12.1
	- minecraft 1.20.4
	- modmenu 9.0.0
	   \-- fabric-resource-loader-v0 0.11.15+78d798af4f
	- presencefootsteps 1.10.0
	- reeses-sodium-options 1.7.0+mc1.20.2-build.97
	- servercountryflags 1.9.4
	- shouldersurfing 2.8.1
	- skinlayers3d 1.6.0
	- sodium 0.5.5
	- sodium-extra 0.5.3+mc1.20.2-build.114
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sound_physics_remastered 1.20.4-1.3.1
	- starlight 1.1.3+fabric.f5dcd1a
	- supermartijn642configlib 1.1.8+a
	- xaerominimap 23.9.6
	- yet_another_config_lib_v3 3.3.1+1.20.4
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1`

**Comment by tr7zw** [comment]
Duplicate #138
