### ISSUE TITLE
Conflict with EmoteCraft

### ISSUE THREAD

**Issue by Baguhan-p** [tr7zw/3d-Skin-Layers#141]
Conflict with EmoteCraft

I use minecraft Fabric/quilt 1.20.1
EmoteCraft 2.2.7 build49
3D Skin Layers 1.6.1

When an emotion is played, the 3d layer is displayed incorrectly. He moves to the side or moves with a lag

![image](https://github.com/tr7zw/3d-Skin-Layers/assets/45269472/0abd68bd-4eaa-4138-884d-469fc7738bd1)
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/45269472/8fbe26cc-bae0-4bfc-8441-7a49fd96eb55)

**Comment by tr7zw** [comment]
The logic for this is inside EmoteCraft, open an issue there.
