### ISSUE TITLE
[1.16.5] Mod can't find fabric api on 1.6.2

### ISSUE THREAD

**Issue by Mr-Beacon00** [tr7zw/3d-Skin-Layers#142]
Minecraft 1.16.5
Fabric 0.15.3
Mod 1.6.2
Fabric API 0.42.0+1.16

can't find fabric api on start up, even i already installed fabric api

I opened mod jar and modified fabric.mod.json, 
at line 30, I changed "fabric-api" to "fabric" and everything just fine.

**Comment by tr7zw** [comment]
Oh Christ, on old mc versions the API was just looking for fabric-api...
