### ISSUE TITLE
Forge Version has Fabric API as dependency

### ISSUE THREAD

**Issue by Einhornyordle** [tr7zw/3d-Skin-Layers#143]
The latest version for (forge 1.6.2-1.20.1 - Forge) [on Modrinth](https://modrinth.com/mod/3dskinlayers/version/z7pEP8p7) has Fabric API as required dependency

**Comment by Einhornyordle** [comment]
Makes sense for the fabric only version, since some launchers won't auto-install the fabric api, unless it is declared as a required dependency, but for the forge version, it just causes issues when forge tries to load the fabric api :sweat_smile:

**Comment by tr7zw** [comment]
Fixed manually for now. Will have to modify the build to not include the fabric mod info file in the forge builds, so mcpublish doesn't auto-add the fabric dependencies.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/ProcessedModTemplate/commit/f12a24a656b46c3ba87518333715c083c717eca7 should fully fix this going forward.
