### ISSUE TITLE
I have a problem with mods and skins in minecraft

### ISSUE THREAD

**Issue by cloudswww** [tr7zw/3d-Skin-Layers#145]
I downloaded the 3skin layer mod and my skin is lagging 
![2024-02-06_21 51 24](https://github.com/tr7zw/3d-Skin-Layers/assets/159158136/f0f54c8b-153e-46bc-aaf7-a476e27fc3d6)
![2024-02-06_21 51 28](https://github.com/tr7zw/3d-Skin-Layers/assets/159158136/3022b447-69aa-4a27-8376-b52471238457)
Minecraft version: 1.20.1
ModLoader: Fabric

**Comment by tr7zw** [comment]
You are using epic fight or some other animation mod that is not supported.
