### ISSUE TITLE
Sudden crash while playing on the server.

### ISSUE THREAD

**Issue by YOMA8338** [tr7zw/3d-Skin-Layers#150]
I do not know why it crashes. And it doesn't crash unless I use this mod.
I'm not sure, so I'm attaching an image of the crash log.
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/167823145/0de52db9-93a3-4d4c-b751-4ec5cf914c89)

**Comment by tr7zw** [comment]
Hm, please test with https://github.com/tr7zw/3d-Skin-Layers/actions/runs/8637886448 (the artifacts button at the bottom of the page, then getting the 1.20.4 fabric jar out of the zip), as this will be the released version later this week with 1.20.5 releasing.

**Comment by YOMA8338** [comment]
Thank you very much. Crash problem solved.
However, the head in the inventory does not appear to be a 3D model.
Is this a bug?

Display in inventory ↓.
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/167823145/9f7e0429-c0fe-4088-9fbc-4b2821fffb3b)

Actual display ↓
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/167823145/1a1885ca-7e8a-4061-b391-a826c82b2165)

**Comment by tr7zw** [comment]
Hm will have to check, maybe the texture didn't load in fast enough, causing a race condition.
