### ISSUE TITLE
Wither skeleton's head could cause it to crash if you look at it.

### ISSUE THREAD

**Issue by YOMA8338** [tr7zw/3d-Skin-Layers#151]
I am the person who previously reported the problem under the title "crashes while playing on the server".
When I crashed before, there was a wither skeleton head there.
When I looked at the contents of the shulker box in the MiniHUD, there was a wither skeleton head there, but when I tried to view it, it crashed.
This leads me to believe that there is a crashing bug in the wither skeleton head.
The crash log is probably the same as before.
This bug is very mysterious as for some reason sometimes it occurs and sometimes it does not.

**Comment by YOMA8338** [comment]
It is possible that there is a lack of specifications.
So I will post the configuration of the PC. It's in Japanese...

![image](https://github.com/tr7zw/3d-Skin-Layers/assets/167823145/3236f607-fd74-4943-9dee-a959361bb4a9)

CPU Intel(R)N95
RAM 8GB
SSD 256GB
Windows11pro 64bitOS x64Base Processor

**Comment by tr7zw** [comment]
Please provide the crash log, mc version mod version etc.

**Comment by YOMA8338** [comment]
Perhaps this is it.
[crash-2024-04-27_13.01.08-client.txt](https://github.com/tr7zw/3d-Skin-Layers/files/15143509/crash-2024-04-27_13.01.08-client.txt)
MCVersion:1.20.4 Fabric 0.15.10
I believe the version of SkinLayer3D was 1.6.5.

**Comment by tr7zw** [comment]
Hm, my guess looking at that crash report, it seems to be due to how 
> fi.dy.masa.malilib.render.InventoryOverlay.renderStackAt

works, used by minihud. I'll add a fix into the next release.
