### ISSUE TITLE
[Feature Request] Compatibility with Ears mod

### ISSUE THREAD

**Issue by Flexico** [tr7zw/3d-Skin-Layers#156]
The [Ears mod](https://ears.unascribed.com/) adds several texture layers for greater character customization, but they're annoyingly flat. Would it be possible for this mod to add thickness to them like it does for the vanilla layers?
![photo_2022-01-26_06-34-20](https://github.com/tr7zw/3d-Skin-Layers/assets/5751770/cf56c5dc-e9ef-4401-89a8-95a09e2c0054)
![photo_2022-02-02_03-59-33](https://github.com/tr7zw/3d-Skin-Layers/assets/5751770/969ba79a-676e-44d1-8ec2-cb57285a00ff)

**Comment by tr7zw** [comment]
I think you should just ask that over on the ears issue tracker. Don't think this is something I will look into.
