### ISSUE TITLE
What is this Crash?

### ISSUE THREAD

**Issue by YOMA8338** [tr7zw/3d-Skin-Layers#157]
The launcher displayed the following.

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "dev.tr7zw.skinlayers.accessor.SkullSettings.getHeadLayers()" because "dev.tr7zw.skinlayers.SkullRendererCache.lastSkull" is null

I will post the crash log.
[crash-2024-05-21_04.10.29-client.txt](https://github.com/tr7zw/3d-Skin-Layers/files/15381014/crash-2024-05-21_04.10.29-client.txt)

If this is by Exordium, it will be posted to Exordium.

**Comment by tr7zw** [comment]
This has nothing to do with Exordium(added to not even being released for 1.20.6). Seems more like an issue with moreculling of itemframes? Weird, will check to add a workaround for the crash.

**Comment by YOMA8338** [comment]
After adding Exordium, I started getting crashes when entering some areas. However, if I enter after the crash, it does not crash.
