### ISSUE TITLE
Launch failed with Capes and Shoulder Surfing Reloaded install on Minecraft 1.21 Quilt 0.26.0

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [tr7zw/3d-Skin-Layers#159]
**Describe the bug**
The game auto reload resources packs and get stuck while launching.

**To Reproduce**
1. Install Minecraft 1.21 with Quilt Loader 0.26.0
2. Add Capes, 3D Skin Layers, Shoulder Surfing Reloaded and all dependencies to mods directory
3. Launch the game
4. Game will auto reload resources packs after progress bar reach the end, and it stuck. But GUI buttons are actully works, you just can't see them

**Expected behavior**
Game should'n reload resources packs and will not stuck

**Screenshots**
![屏幕截图_20240623_155040](https://github.com/CaelTheColher/Capes/assets/97139537/6710a73d-c1b0-4b52-ad32-e61548f8a9ca)

**Debug info**
Game log: https://mclo.gs/oZontXQ

**Context:**
 - Minecraft version: 1.21
 - Shoulder Surfing Reloaded version: 1.6.6
 - Mod list:
    - [Capes](https://modrinth.com/mod/89Wsn8GD) [1.5.4+1.21]
    - [Fabric API](https://modrinth.com/mod/P7dR8mSH) [0.100.3+1.21]
    - [Fabric Language Kotlin](https://modrinth.com/mod/Ha28R6CL) [1.11.0+kotlin.2.0.0]
    - [Shoulder Surfing Reloaded](https://modrinth.com/mod/kepjj2sy) [4.1.5]
    - [Forge Config API Port](https://modrinth.com/mod/ohNO6lps) [21.0.0]
      [3d-Skin-Layers](https://modrinth.com/mod/zV5r3pPn) [1.6.6]
- Server: N/A

**Additional context**
I also opened issues for Capes and Shoulder Surfing Reloaded. See https://github.com/CaelTheColher/Capes/issues/135 https://github.com/Exopandora/ShoulderSurfing/issues/220

**Comment by tr7zw** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector fixCapeTransparency(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; in #capes:capes-common.mixins.json:MixinCapeFeatureRenderer from mod capes failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap capes-common-refmap.json

>  | [15:43:23] [Render thread/WARN]: @Redirect conflict. Skipping #capes:capes-common.mixins.json:MixinCapeFeatureRenderer from mod capes->@Redirect::fixCapeTransparency(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; with priority 1000, already redirected by #shouldersurfing:shouldersurfing.common.mixins.json:MixinCapeLayer from mod shouldersurfing->@Redirect::entitySolid(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; with priority 1000

Has nothing to do with this mod. Shoulder surfer and capes are just incompatible with each other.
