### ISSUE TITLE
zh_cn translations update

### ISSUE THREAD

**Issue by 70CentsApple** [tr7zw/3d-Skin-Layers#164]
It would be nice to copy [zh_cn.json in branch 1.20.2](https://github.com/tr7zw/3d-Skin-Layers/blob/1.20.2/Shared/src/main/resources/assets/3dskinlayers/lang/zh_cn.json) to the [main branch](https://github.com/tr7zw/3d-Skin-Layers/blob/main/src/main/resources/assets/skinlayers3d/lang/zh_cn.json).

**Comment by tr7zw** [comment]
Interesting, the PR was probably made to the wrong branch back then, getting it lost in time.
