### ISSUE TITLE
Incompatibility with Custom Player Models / Add render switch shortcut key

### ISSUE THREAD

**Issue by XiaoTDM** [tr7zw/3d-Skin-Layers#171]
When used with Custom Player Models, it causes 3D layers to be overlaid on custom models.
Is it possible to consider compatibility adaptation and disable rendering when CPM is detected?

If this is not possible, it is recommended to add a shortcut key to toggle the render state.

**Comment by tr7zw** [comment]
Duplicate #125 , also potentially try the new compatibility mode in the settings.
