### ISSUE TITLE
Incompatible with fresh moves

### ISSUE THREAD

**Issue by carc1n0gen** [tr7zw/3d-Skin-Layers#172]
With the [fresh moves](https://modrinth.com/resourcepack/tras-fresh-player) resource pack, which requires [entity models](https://modrinth.com/mod/entity-model-features) and [entity textures](https://modrinth.com/mod/entitytexturefeatures) mods, the outer layer of the hands move separate from the rest of the player skin.
![ezgif-5-8793b3e881](https://github.com/user-attachments/assets/55abc90f-82c4-4a49-800a-c7eb8beffed4)

**Comment by tr7zw** [comment]
You need to follow the guide on the resource pack site to turn off the animations applying in first person.
