### ISSUE TITLE
Small but significant issue.

### ISSUE THREAD

**Issue by The-Goat591** [tr7zw/3d-Skin-Layers#175]
I'm just playing minecraft with the mod installed and using Complementary Unbound when i grab a diamond sword that shines and the 3D pixels shine as well. Also happens with any other item that has reflection a long with command blocks that make the pixels glow.

**Comment by tr7zw** [comment]
That sounds like an issue with iris or complementary then? At least this wasn't an issue before and nothing really changed at all in recent times.

**Comment by The-Goat591** [comment]
Thx a lot! It makes sense its an iris feature.Sent from my iPhoneOn Sep 6, 2024, at 3:39 PM, tr7zw ***@***.***> wrote:﻿
That sounds like an issue with iris or complementary then? At least this wasn't an issue before and nothing really changed at all in recent times.

**Comment by tr7zw** [comment]
This should be fixed with the new compatibility mode.
