### ISSUE TITLE
Bug with player animator

### ISSUE THREAD

**Issue by RazorPlay01** [tr7zw/3d-Skin-Layers#178]
Basically when modifying the player animations using the player animator api the second layer of the skin ends up separating from the body at least the head part I have not tried with another skin to be honest.
https://youtu.be/xmY1fmuuBN4

**Comment by tr7zw** [comment]
Hm will have to test with BetterCombat and Emotecraft. It certainly used to work.

**Comment by RazorPlay01** [comment]
it's probably something in the latest version of player animator for minecraft 1.21, I had also used it before and it didn't happen

**Comment by RazorPlay01** [comment]
Problem solved in the last pull request from ZigyTheBird to PlayerAnimator, they were trying to fix a bug with the layers when using animations made with geckolib and it seems that this mod had been broken.

**Comment by tr7zw** [comment]
Huh interesting

**Comment by RazorPlay01** [comment]
Indeed, it seems that both the layer 2 of the player's skin and the cape were being repositioned according to the same point of the body when playing the animation and having your animations in which the cape was broken the layers 2 of the skin suffered the same fate, but it seems to be all fixed.
