### ISSUE TITLE
Error 1.12.2TL ForgeOptifine

### ISSUE THREAD

**Issue by NicoNicoNicoNicoNicoNicoNicoNicoNico** [tr7zw/3d-Skin-Layers#179]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-09-17 19:58:28 CDT
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1131)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 602212896 bytes (574 MB) / 1073741824 bytes (1024 MB) up to 3154116608 bytes (3008 MB)
  JVM Flags: 7 total; -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 44 mods loaded, 44 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                         | Version                | Source                                                       | Signature                                |
       |:----- |:-------------------------- |:---------------------- |:------------------------------------------------------------ |:---------------------------------------- |
       | L     | minecraft                  | 1.12.2                 | minecraft.jar                                                | None                                     |
       | L     | mcp                        | 9.42                   | minecraft.jar                                                | None                                     |
       | L     | FML                        | 8.0.99.99              | forge-1.12.2-14.23.5.2860.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge                      | 14.23.5.2860           | forge-1.12.2-14.23.5.2860.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | skinlayers3d               | 1.2.0                  | 3dSkinLayers-forge-mc1.12.2-1.2.0.jar                        | None                                     |
       | L     | magistuarmory              | 1.0                    | [1.12.2]-Epic-Knights-Armor-and-Weapons-6.2v(uncomplete).jar | None                                     |
       | L     | atlaslib                   | 1.1.5a                 | Atlas-Lib-1.12.2-1.1.5a.jar                                  | None                                     |
       | L     | betterbuilderswands        | 0.11.1                 | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar              | None                                     |
       | L     | blue_skies                 | 1.1.3                  | blue_skies-1.12.2-v1.1.3.jar                                 | None                                     |
       | L     | dawnoftimebuilder          | 1.0.7                  | dawnoftime_builder_edition-1.0.7.jar                         | None                                     |
       | L     | dynamictrees               | 1.12.2-0.9.29          | DynamicTrees-1.12.2-0.9.29.jar                               | None                                     |
       | L     | net.blacklab.lib           | 6.0.2.5                | EBLib-6.0.2.5.jar                                            | None                                     |
       | L     | engineersdecor             | 1.1.5                  | engineersdecor-1.12.2-1.1.5.jar                              | None                                     |
       | L     | sexmod                     | 1.1.0                  | Fapcraft 1.12.2 v1.1.jar                                     | None                                     |
       | L     | geckolib3                  | 3.0.30                 | Fapcraft 1.12.2 v1.1.jar                                     | None                                     |
       | L     | flansmod                   | 5.5.2                  | Flan's Mod-1.12.2-5.5.2.jar                                  | None                                     |
       | L     | flansmodapocalypse         | 1.0                    | Flan's Mod-1.12.2-5.5.2.jar                                  | None                                     |
       | L     | industrialrenewal          | 0.21.8                 | IndustrialRenewal_1.12.2-0.21.8.jar                          | None                                     |
       | L     | landlust                   | 1.12.2-0.3.6           | landlust-1.12.2-0.3.6.jar                                    | None                                     |
       | L     | lmreengaged                | 8.0.1.66               | LittleMaidReengaged-8.0.1.66-unofficial-1.12.2.jar           | None                                     |
       | L     | mcwbridges                 | 1.0.6                  | mcw-bridges-1.0.6b-mc1.12.2.jar                              | None                                     |
       | L     | mcwdoors                   | 1.3                    | mcw-doors-1.0.3-mc1.12.2.jar                                 | None                                     |
       | L     | mcwfences                  | 1.0.0                  | mcw-fences-1.0.0-mc1.12.2.jar                                | None                                     |
       | L     | mcwfurnitures              | 1.0.1                  | mcw-furniture-1.0.1-mc1.12.2beta.jar                         | None                                     |
       | L     | mcwlights                  | 1.0.6                  | mcw-lights-1.0.6-mc1.12.2forge.jar                           | None                                     |
       | L     | mcwtrpdoors                | 1.0.2                  | mcw-trapdoors-1.0.3-mc1.12.2.jar                             | None                                     |
       | L     | llibrary                   | 1.7.20                 | llibrary-1.7.20-1.12.2.jar                                   | None                                     |
       | L     | mowziesmobs                | 1.5.8                  | mowziesmobs_1.12.2_1.5.8.jar                                 | None                                     |
       | L     | spartanshields             | 1.5.5                  | SpartanShields-1.12.2-1.5.5.jar                              | None                                     |
       | L     | spartanweaponry            | 1.6.0                  | SpartanWeaponry-1.12.2-1.6.0.jar                             | None                                     |
       | L     | hordes                     | 1.5.3a                 | The-Hordes-1.12.2-1.5.3a.jar                                 | None                                     |
       | L     | tlauncher_custom_cape_skin | 1.4                    | tlskincape_1.12.2-1.4.jar                                    | None                                     |
       | L     | vanillafix                 | 1.0.10-SNAPSHOT        | VanillaFix-1.0.10-99.jar                                     | None                                     |
       | L     | betteranimalsplus          | 9.0.1                  | betteranimalsplus-1.12.2-9.0.1.jar                           | None                                     |
       | L     | drplibrary                 | 1.12.2-0.1.3-SNAPSHOT  | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.024240.jar         | None                                     |
       | L     | drpcmblueprints            | 1.12.2-1.2.3           | drpcmblueprints-1.12.2-1.2.3.jar                             | None                                     |
       | L     | drpcmmaarg                 | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.064036.jar        | None                                     |
       | L     | drpcmguis                  | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.110253.jar          | None                                     |
       | L     | drpcore                    | 1.12.2-0.4.7           | drpcore-1.12.2-0.4.8.jar                                     | None                                     |
       | L     | drpcmlocks                 | 1.12.2-1.0.1           | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.101203.jar         | None                                     |
       | L     | drpmedieval                | 1.12.2-0.3.6           | drpmedieval-1.12.2-0.3.6.jar                                 | None                                     |
       | L     | immersiveengineering       | 0.12-98                | ImmersiveEngineering-0.12-98.jar                             | None                                     |
       | L     | ironagefurniture           | 0.2.0.5                | ironagefurniture 1.12.2 v0.2.0.5.jar                         | None                                     |
       | L     | phosphor-lighting          | 1.12.2-0.2.6           | phosphor-1.12.2-0.2.6+build50-universal.jar                  | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.6.0.jar)
                                        
                                      TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
                                        gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.51' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: ForgeOptiFine 1.12.2
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.51, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Scary Spider 1.11+.zip, Better_Farm_Animals_V0.07.zip (incompatible)
  Current Language: Español (España)
  Profiler Position: N/A (disabled)
  CPU: 2x AMD Athlon(tm) II X2 215 Processor

**Comment by NicoNicoNicoNicoNicoNicoNicoNicoNico** [comment]
i tried updating java and i still getting the same error

**Comment by NicoNicoNicoNicoNicoNicoNicoNicoNico** [comment]
Atlas Lib causes troubles

**Comment by NicoNicoNicoNicoNicoNicoNicoNicoNico** [comment]
if i remove vanillafix the game enterily crashes

**Comment by NicoNicoNicoNicoNicoNicoNicoNicoNico** [comment]
ok incompatibility with most of mods i have installed

**Comment by tr7zw** [comment]
That's the mixin loader crashing, not the mod. Also cracked Mc.
