### ISSUE TITLE
Your mods are added to the modpack in China and charged/你的模组在中国被加入整合包并且收费(Using an electronic translator/使用电子翻译器)

### ISSUE THREAD

**Issue by shenxiaochuan258** [tr7zw/3d-Skin-Layers#183]
Paid links for this person/此人的收费链接
https://afdian.com/a/Aming666?tab=feed

**Comment by tr7zw** [comment]
Paid modpacks? China is wild, I'll look into it.

**Comment by itzme1on** [comment]
I also received a similar message xD

**Comment by shenxiaochuan258** [comment]
> 付费 Modpack？中国很狂野，我会调查一下。

Here's his promotional video
https://www.bilibili.com/video/BV12XxQeUEQS/?spm_id_from=333.999.top_right_bar_window_history.content.click&vd_source=12ec42f91b7a5bf6a8615a9b15c57e07

**Comment by shenxiaochuan258** [comment]
> 我也收到了类似的消息 xD
Can you tell us which modpack it is?
可以说一下具体是哪个整合包吗？

**Comment by shenxiaochuan258** [comment]
> 我也收到了类似的消息 xD

Yes, that guy is a scumbag thief who mixes a lot of mods together and sells them for money/是的，那个人就是个卑鄙的小偷，把大量模组混合在一起就卖钱

**Comment by tr7zw** [comment]
Apparently you can't message people on that site without paying them first. So instead filing a copyright notice, as rehosting the mod and taking a commercial advantage of it (which would be paid clients/modpacks) is against the license.

**Comment by shenxiaochuan258** [comment]
> 显然，如果不先付款，你就不能向该网站上的人发送消息。因此，反而提交版权声明，因为重新托管 Mod 并利用它（这将是付费客户/modpacks）是违反许可证的。

Do you need a download link?/你需要下载链接吗？

**Comment by shenxiaochuan258** [comment]
> 显然，如果不先付款，你就不能向该网站上的人发送消息。因此，反而提交版权声明，因为重新托管 Mod 并利用它（这将是付费客户/modpacks）是违反许可证的。

https://www.123pan.com/s/SdryVv-gOTJH.html
![D3AB5F7D080119BAE9202D5A43EBE4F9](https://github.com/user-attachments/assets/de7a380b-038b-4a8a-beba-1d592f61ad70)

**Comment by tr7zw** [comment]
Hm that is a normal modpack file, so hes not rehosting that mod(but other peoples mods are indeed in there), still in violation of the license.

**Comment by shenxiaochuan258** [comment]
> 嗯，这是一个普通的 modpack 文件，所以他没有重新托管那个 mod（但其他人的 mod 确实在那里），仍然违反了许可证。

ok

**Comment by tr7zw** [comment]
They seem to have been taken down.
