### ISSUE TITLE
incorrect operation of the mod with Fabric 1.20.1 version

### ISSUE THREAD

**Issue by StarEnd01** [tr7zw/3d-Skin-Layers#185]
Hello, can you solve this problem? Please this is important to me
This mod does not work correctly with fabric 1.20.1, even though I have the appropriate version of fabric-api installed, and I also sent you a picture of the error and proof of the mods in the folder.
![photo_2024-10-24_19-32-55](https://github.com/user-attachments/assets/c2631c02-313f-4cb8-9160-c99af1648694)
![photo_2024-10-24_19-33-01](https://github.com/user-attachments/assets/589bff62-a969-4bbe-acde-2cf70322c4ca)
![photo_2024-10-24_19-35-14](https://github.com/user-attachments/assets/807e932a-a487-49a2-90e4-0a4e211208ee)

**Comment by tr7zw** [comment]
You have a cracked version of the game, thats why. Buy the game, remove tl_skin_cape and it will work correctly.

**Comment by StarEnd01** [comment]
Oh, I get it. If I get the chance, I'll buy it. Thank you for answering
