### ISSUE TITLE
Rendering Entity in World (1.16.5)

### ISSUE THREAD

**Issue by Coraline77447** [tr7zw/3d-Skin-Layers#19]
Minecraft: 1.16.5
Forge: 36.2.8
Skin Layers 3D: 1.1.0 (Forge)

The game crashes when I'm loading into an existing world and I think that the game would crash with only this mod installed with Optifine and Better First Person Model mod in a freshly created world, doesn't matter but if you insist that I test with only the mods I'd mentioned above with Skin Layers 3D and create a new world then I'll do so but for now I'll provide the crash report and log.

Crash Report: https://pastebin.com/Wbub96my

Log: [latest.log](https://github.com/tr7zw/3d-Skin-Layers/files/7529541/latest.log)

**Comment by tr7zw** [comment]
I mean the First Person mod is by me, and the 3 have been tested with optifine, so that should be fine. Somehow it thinks that you have a skin when you actually don't(or its not yet loaded).
![grafik](https://user-images.githubusercontent.com/5133936/141515012-b7a266a6-0805-40df-a7ed-3f0820d4081c.png)
(1.16.5 Forge Optifine + First Person + 3d skins)
I guess I'll add a failsave check at that place, in case some other mod screws with that logic.

**Comment by Coraline77447** [comment]
UPDATE: I'd made a fresh test world with only this mod along with Optifine and I've successfully loaded into the test world. 
So now this has turned from a mod not working at all for some unknown reason report to a mod confliction report and now I'll have to know which mod is causing this.

Also I'd forgot to mention that I'd gave this mod a try on a different preexisting modded world and may have crashed the same way as it did this time with the modded world I'd made yesterday.

Unfortunately I'm not willing/going to waste anymore time tryin to figure out which mod is the cooperate for Skin Layers 3D to not work alongside with whatever mod is causing this by taking mods out one at a time ot groups at a time till I find the one that's causing this is because I'm going to start playing on my latest modded world that was created yesterday right now...

But when I'd looked at the crash report it was sayin somethin about Twilight Forest which the world that I've made yesterday has that mod, so did the other world as well. 
(both of these modded worlds are called Coraline World 5: T.F.T.I.C and Coraline World 6, Coraline world 5's mod list is practically the same as Coraline World 6 except that Coraline World 5 has a few more mods than Coraline World 6)

Really wanted to see how my current skin would look like in 3D instead of how it looks like right now, still looks good but could look better with this mod....

**Comment by tr7zw** [comment]
https://github.com/tr7zw/3d-Skin-Layers/actions/runs/1454280311 download and try this build once github is done building it. It should at least prevent it from crashing.

**Comment by Coraline77447** [comment]
Okay

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/141520538-39045cda-c2fa-4120-9e43-f6c4e1cb9509.png)
and in the zip you find the fabric and forge build in the folders.

**Comment by Coraline77447** [comment]
Update 2: Tried to use the main build from the link that ya sent me and failed to load into the test world, insa crashed after I'd insta spawned into the test world. Then I tried the dev build under the main build and it worked!

**Comment by tr7zw** [comment]
Wait what? What build did you use?

**Comment by Coraline77447** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/72243304/141522583-3fbc7bc8-3e35-4524-babd-fe02e05539ca.png)

The bottom one

**Comment by tr7zw** [comment]
That build 100% doesn't work in a runtime build. the -dev jar only works for development environments.

**Comment by Coraline77447** [comment]
I'd foliowed your instructions exactly which lead me to the folder Libs as it's called and tried the top one and like I said above that apoun loading in and saw the test world itself for a split second, then the game crashed. 
I also know that the bottom one is for dev environments which has your new fail safe which apparently you may have put it in the main build but for some reason it's not working for me, even tho I may not be the only one (hope not). 

The mod may work for some people but some like me would run into issues with said mod. 
Also do we need to officially own the game and use the official launcher for the mod to detect the person's Minecraft skin?

Since I use Tlauncher for modding in older versions like 1.16.5 which I'm using my custom skin that I made on an app for bedrock edition called Skinseed for Tlauncher until 1.17+. 

In 1.17+ I use the official launcher (that a friend gave me a redeem code for minecraft java edition, and already added my curent custom skin too as well) for modded Minecraft until forge 37.0.31 when the forge devs made some game breaking changes which ultimately "killed" (they're not actually dead) 15 mods or had put 15 mods out of commotion that I was playing with at the time. 

Then I'd stopped playing modded 1.17.1 after that and still waiting for a stable release of forge 1.17.1 for the last 2+ months so that I wouldn't get hit repeatedly by forges issues. Sure I'll still run into problems with forge 1.17.1 in it's stable builds but at least it's stable builds will hopfully be alot better and stable than it's beta builds, especially better and stable than it's early beta builds 2+ months ago..
(sorry fot the long response btw...)

**Comment by tr7zw** [comment]
Ahh yea there is a good possibility that it just 100% doesn't work with TLauncher(buy the game^^). Also the dev jar is not the dev build I just made. It's the same as the non dev jar in the same folder, just mapped for development with Forge.
Just a few things: 1) buy the game, I can't/won't spend time to get illegal versions running correctly 2) don't use Forge if possible, it sucks(use fabric instead, all my mods are already out for 1.18-pre1/release)

**Comment by Coraline77447** [comment]
I don't use fabric and most of my favorite mods like A.O.A (Advent of Ascension), Twilight Forest, and Tinkers' Construct are exclusively for forge, I think that someone is making a fabric port of Tinkers but that info was a while ago and can't really remember that info exactly. 

Some of the mods I've been playing with for the last 5+ years (since 1.12.2 in 2016 or 2017) have always been forge mods and won't ever have a fabric port, also fabric may not have some of the capabilities that forge has even tho as you said, what everyone else says and I even say to myself sometimes that forge does suck since it's a decade old and the devs (Lux) are outright duchebags that they're rude, mean and disrespectful to the modding community that they don't care about the modding community.. 

I do have a copy of the game cause a friend in a DM on discord legit gave me a redeem code for MC java edition, but for 1.16.5 and below I prefer to use Tlauncher over the official launcher. 

Especially in task manager the official launcher uses two or three more background processes than Tlauncher which I want less background processes for more performance and FPS in my modded gameplay.

Even tho terminating background processes doesn't really do much thesedays but at least it does improve performance and FPS to some degree (Windows is just too bloated with processes and starting to dislike windows but still using windows anyways).

I wasn't sure if I really to share what I'd said above about what launcher I use because I already knew what you would say about that and I imagined that you wouldn't be too happy to know that I was once and kinda still am a cracked client user for MC and would do somethin like report me or somethin that wouldn't end too well for me cause I want to keep playing MC and modded minecraft. 

But that may have somethin to do about Skin Layers 3D not working with TLauncher since your other mod Better First Person Model works just fine with the rest of my mods list for two worlds that I have when I use TLauncher. (Btw I'm havin a blast with BFPM aka Better First Person Model! Really like seeing what others sees as of the animations and makes the drawing back animation for the bow alot better from a third person prospective while in first person)

Why I used third party launchers for as long as I had right up till 1.17 was cause I didn't have the cash for the game but really wanted to play MC because of my favorite minecraft youtubers YouAlwaysWin (now 2PixelBros, same youtubers btw) so that I could experience the game myself and have my own adventures.

One very last thing, are you mad at me because I used and may still use pirated launchers despite owning a copy of the game to play on new versions of the game?....

**Comment by tr7zw** [comment]
I'm not mad, it's just that tlauncher just causes issues with anything capes/skins(for no good reason) and it's only use case is piracy, so I don't support it^^.  
> also fabric may not have some of the capabilities that forge has

That's wrong, there is nothing you can't do in Forge you can't do in Fabric and vice versa. Both give you the option to do whatever the heck you want(as a developer), the only difference is the tooling around it. 
And usually, the thing is that devs are hard stuck on <= 1.16 Forge, but there is a mod implementing the mod 1:1 as a modern Fabric mod. Or mods like Twilight Forest become negligible with better alternatives world exploration mods like BetterEnd/BetterNether or replacing Optifine with iris+sodium+lithium+starlight. So going "but mod xyz is not on Fabric" is usually invalid because there is mod ABC that does the same thing, but is just called differently(Lists like https://gist.github.com/TrueCP6/4853f15015b210fd3b1e210e9e485f83 might help to find replacements for Tinkers, applied energetics, witchery, drawers etc).

**Comment by Coraline77447** [comment]
Hey, I'm going to try modded 1.17.1 once again, been thinking about trying modded 1.17.1 again lately after the last time I played on 1.17.1 modded on forge before forge 1/17/1 37.0.31. 

37.0.31, the version that caused the most damage to all mods that adds tools and related items to tools and the main reason why I stopped modding 1.17.1 a few months ago. 
Even tho I would prefer to wait till the forge devs releases 37.1.0 as an actual stable build but I guess 37.0.109 is as stable as it can get at the moment and I do miss playing modded 1.17.1 while I'm starting to get bored of playing on the same 1.16.5 modded worlds and want to add 1.17.1 modded into the mix and yes I'll be using the official launcher since I'll always use the official launcher for 1.17+.

I only use/used TLauncher for modding older versions of Minecraft such as 1.16.5 and 1.12.2, if I'll ever come back to 1.12.2 that is, probably not)
Despite the official launcher using more background processes than pirated launchers such as Tlauncher I'm willing to sacrifice some of my RAM and framerate to use the official launcher so that I would finally stop using illegal launchers and getting myself into a sticky situation (not related to the advancement "A Sticky Situation" from Minecraft 1.15 aka the Busy Bees Update, lol) with the law and everything..

So now I'll give 3D Skin Layers a second chance in 1.17.1 forge (not fabric, sorry..). 
Can't wait to see how my custom skin will look like, hope it'll look like how I'm imagining it to be alongside Better First Person Model for 1.17.1.

P.S. I'm gonna stop talkin about Tlauncher and anything related with it so that I wouldn't be annoying while continuing to talk about that when I don't like talkin about that... 
Im letting it go already, also if we would be having actual convocation(s) about your mods then I probably should just join your discord server and talk about your mods there instead of on this closed issue report's comment section or if we would just want to talk on there instead of in this closed issue report's comment section..

**Comment by tr7zw** [comment]
I released a new update for 1.18 and 1.17 today, so you can give that a try, since it looks better on most skins. The Vanilla launcher background process issue is news to me, probably because I'm not really in a target group for that(ryzen 5600x, 32gb ram, rtx 2070super^^). I kinda decided to not push updated to 1.16 anymore since it's more work than it's worth at this point(in 11 days it's outdated by 2 versions). I don't use anything provided by forge at all (other than adding the menu screen), so using whatever forge version should be fine.

**Comment by Coraline77447** [comment]
I wanna show ya something important regarding my edited MC skin that I'd edited on a website called Miners Needs Cool Shoes;
(Screenshots were taken on my modded 1.17.1 world, also does it look good despite the problem that I've discovered which was supposedly fixed;

![Inked2021-11-22_03 52 35_LI](https://user-images.githubusercontent.com/72243304/142852323-794092ce-684f-467f-9585-859ec467b456.jpg)

![Inked2021-11-22_03 53 08_LI](https://user-images.githubusercontent.com/72243304/142852353-17f003a8-7fed-4e4e-bd63-ced2f4db96b1.jpg)

![Inked2021-11-22_03 53 55_LI](https://user-images.githubusercontent.com/72243304/142852374-58b8fc71-8db3-4fa4-b38d-09cdba3d34ed.jpg)

![Inked2021-11-22_03 54 24_LI](https://user-images.githubusercontent.com/72243304/142852426-980d6588-b07a-4ff4-a56f-9d5d9c3a7409.jpg)

**Comment by tr7zw** [comment]
It's a cube. Thats why you can see it around the corner like that.

**Comment by Coraline77447** [comment]
Tbh what's in the circles that I'd drew doesn't bother me that much since I dont see those cubes as much, especially since I'm playing with your other mod Better First Person Model mod. Unless I tap F6 to switch back to normal view with my main hand showing then I could possibly see the one that can be seen in the second screenshot.
I Also tend to tap F6 to turn FPM off and on only when I'm using a fishing rod when I go fishing since the line visually isn't attached to the rod when the line is casted out, that visual problem was in MC in the past till Mojang fixed it several years ago but apparently with FPM the fishing rod visual problem comes back.

(Btw I'm not playing on the world that I'd took the screenshots on anymore since I'd figured out what mod(s) was causing Twilight Forest for 1.17.1 to crash the game, one of them being OptiFine. 
Some rendering overlay issue that the launcher was telling me and I'd never had a thought about OptiFine and as the good old saying goes always suspect and blame OptiFine for its rendering issues with other mods, apparently like Twilight Forest. 
Thought that the rendering overlay thing was coming from one of the other mods that I'm playing with but really was from OptiFine aka Fartfine as I'd like to call it nowadays since it really is a piece of shit. 
Only thing I use OptiFine for is its dynamic lighting and its opti-zoom until the spyglass was added to MC 1.17 which replaces the need for  Optifine's zoom feature since the spyglass is like opti-zoom but more vanilla feel and less wide FOV than opti-zoom and with the opti-zoom it's like you've tapped F7..
So now in 1.17+ I would only use Optifine's dynamic lighting until I run into one of my other mods that I'm playing with not liking OptiFine *"cough"* *"cough"* **Twilight Forest** *"cough"*.
Then I'll have to go find a dynamic lighting mod to replace OptiFine despite taking the performance hit from said mod..)

**Comment by tr7zw** [comment]
The fishing rod issue is a result of the player model getting pushed back to be a bit behind the camera. I think this was fixed in the mod at some point to correct the fishing line for that, which first person version do you use?
And yes Optifine is kinda broken with other mods, especially in 1.17. In case you ever switch to Fabric check out Sodium+Lithium(Iris if you play with shaders) instead. They have better compatibility with other mods, are open source, and result in more fps than Optifine reaches.

**Comment by Coraline77447** [comment]
I'm not using Optifine due to Twilight Forest's 1.17 port but the version of First Person I'm currently using is; 2.1.0.

Also what's strange and unusual is whenever I plug in my gaming computer while in a MC play session that the framerate increases, I know that using a device while it's charging decreases the battery's overall lifespan but if my framerate gets improved while the computer is charging then I don't theoretically speaking need Optifine at all.
Btw I've managed to find alternatives to Optifine's features that I like the most which are the dynamic lighting and the zoom feature, the zoom feature was replaced with the Spyglass that Mojang added in 1.17 while that mod replaced the dynamic lighting in Optifine is a mod called Lucent. 
I had found a mod that does dynamic lighting back in the early days of modded 1.17 when optifine wasn't fully compatible with forge (still isn't right now but to some degree it is) but the downside to that mod is that it hit my framerates to the point that I'd uninstalled said mod and sacrificed dynamic lighting for more framerates. That was before forge 37.0.31.

I've heard of Sodium and earlier today I was doing more research on the debate with forge and fabric and at the end of the day it all boils down to your computer as of it's hardware and software. 
That's what the real "enemy" is is our own computers as of how capable they are at what we're trying to use them for, along side that is money as well.
People like me who don't have any to no money at all can't afford a decent computer that's more than capable of running any game flawlessly. 
Sure I could simply go find a job but even if I were to have one I still wouldn't really be able to afford a decent gaming computer that can go as high as $1.000+.
My dream gaming machine that I wish for doesn't exist since all of the computer tech companies doesn't do that like build a computer that has the latest Invidia GForce graphics card along side with the latest, best, most powerful processor on the market and 16+ GB of RAM so that I could reach over 700 framerate like Pat from PopularMMO's does in Minecraft.
So that I wouldn't have to worry about lag and RAM ever again and to be able to actually play big modpacks with no worries, with the exception of mod incompatibilities and all keybinds taken and with keybind conflicts in such a mess since keyboards don't have enough keys to assign all of the mods to a specific keybind. 

Also don't bind any mods to the Tab key or else Open GL wouldn't like that like how I had ToolBelt mod binded with the Tab keyand was getting Open GL errors every time I tapped and healed down Tab (I have Show OpenGL Errors turned off btw)...

**Comment by Coraline77447** [comment]
Btw while I was gonna test my framerate in-game (since I had to remove some mods for more framerate..) in the Minecraft Game Output (which I have enabled so that I can see what's going on during mod loading in case the game crashes during mod loading) I'm seeing this;

16:32:02.899 [16:32:02] [main/ERROR] [mixin/]: Mixin config clumps.mixins.json does not specify "minVersion" property
**_16:32:02.962 [16:32:02] [main/ERROR] [mixin/]: Mixin config firstperson.mixins.json does not specify "minVersion" property_**
16:32:03.005 [16:32:03] [main/ERROR] [mixin/]: Mixin config notenoughcrashes.mixins.json does not specify "minVersion" property
16:32:03.014 [16:32:03] [main/ERROR] [mixin/]: Mixin config notenoughcrashes.forge.mixins.json does not specify "minVersion" property

 Three out of the four are two different mods that I'm playing with, this is near the top of the Minecraft Game Output.
