### ISSUE TITLE
[Bug] Hand Second Layer skin in the first person view doesn't rendered at all

### ISSUE THREAD

**Issue by SteveKunG** [tr7zw/3d-Skin-Layers#190]
As title explains, my second layer skin in the first person view is not rendered.
Skin Customization for all parts are already turn on.

![image](https://github.com/user-attachments/assets/d99d4c35-10d3-442e-9c8a-9fec3db04110)

Mods :
fabric-api-0.107.0+1.21.1
skinlayers3d-fabric-1.7.0-mc1.21

**Comment by SteveKunG** [comment]
Oops, I was an idiot. For anyone else who reads here you'll need to turn on "Compatibility mode" in the mod setting.

**Comment by tr7zw** [comment]
Known bug, currently working on a fix.
