### ISSUE TITLE
ETF Mod's blinking feature makes glowing transparent pixels flicker

### ISSUE THREAD

**Issue by BrightDarknessXX** [tr7zw/3d-Skin-Layers#193]
**What to do:**
1. Join a world with a Skin that has transparent pixels on the top layer.
2. Select transparent pixels to be emissive in ETF. (Entity Model Features > Textures > Player skin settings > Open skin feature tool > Emissive pixels: ON and "Select pixels") 
3. Enable the blinking feature in ETF. (Entity Model Features > Textures > Player skin settings > Open skin feature tool > Blink: * and Eye position: *)

**Expected result:** Nothing blinks except the blinking feature set by Entity Model Features.

**Actual result:** The transparent pixels that were set to be emissive by ETF are now blinking in sync with the blinking features set by ETF.

**Additional information:** Please note that those pixels are also not rendering the lower layer of the Skin when looking at the Skin from some angles. That means you can see through the entire Skin.
I also made a video:
https://youtu.be/YSZyaPtrNVo

**Software used:**
Minecraft 1.20.2
[ETF] Entity Texture Features v6.2.7
3D Skin Layers v1.7.0
Sodium v0.5.5
Fabric-API v0.91.6

**Comment by tr7zw** [comment]
Thats an ETF feature, up to ETF.
