### ISSUE TITLE
3d skin layer not working properly with fresh moves resource pack on 1.21.3 version

### ISSUE THREAD

**Issue by Wunkrap** [tr7zw/3d-Skin-Layers#195]
with the resource pack:
![incompatible](https://github.com/user-attachments/assets/8d5bc35b-75ae-466c-85e7-0a88ba1b9e9c)

**Comment by TheFarix** [comment]
This appears to be a Fresh Moves issue because I have the same problem when uninstalling 3D Skin Layer.

**Comment by Wunkrap** [comment]
Hmmm, maybe, but its strange cause I've been using the same resource pack in 1.21.1 and everything worked properly.....

**Comment by tr7zw** [comment]
Yes, the pack needs to update for 1.21.3. I'm not aware of any animation pack that currently works correctly in 1.21.3.

**Comment by Wunkrap** [comment]
Oh ok that's fine, I'll just wait for the update. Thx for the help!
