### ISSUE TITLE
First Person Voxel Size Cannot Be Changed

### ISSUE THREAD

**Issue by LobbyLC** [tr7zw/3d-Skin-Layers#196]
Despite "Fix firstperson arm layer not working in pre 1.21.3" being listed in the most recent changelog, the feature still doesn't work as intended. Increasing or decreasing the voxel size in the config screen doesn't make a difference in-game. I've attached a demonstration below.

- Here is my config. First Person Voxel Size has been lowered from 1.099 to 1.019
![Config Screen](https://github.com/user-attachments/assets/e8fb7918-81fa-4b60-9160-aacc10783899)

- My arm should not look as 3D as it does (currently, it looks the same as it would with default config)
![In-Game](https://github.com/user-attachments/assets/67731ac4-2809-4149-9496-6756a317c4ad)

(This issue is reproducable when using the latest version of 3D Skin Layers (and no other mods) on Minecraft 1.21.1)

**Comment by tr7zw** [comment]
I don't think it applied before the update either? This would probably need a new slider.

**Comment by LobbyLC** [comment]
I took a look at the changelog to possibly find a solution, and noticed that the way the arm in first-person is rendered was changed in the 1.7.0 release. Could this be relevant to the issue? 🤔

**Comment by tr7zw** [comment]
To clarify: the way the rendering of the firstperson arm works was entirely reworked in 1.7.0. The old one is really buggy, rendered in the wrong location, wrong scale, not connected correctly to the arm. The new one has that all fixed. The only "issue" is that the arm layer size doesn't apply anymore, but I'll be honest, it was never intended to apply the firstperson arm. So this is a feature request for a new slider to be able to change that scale.

**Comment by LobbyLC** [comment]
Ah, gotcha.

But then, out of interest, what is the intended purpose of the "First Person Voxel Size" slider now? It appears to just not have a function as of 1.7.0, but perhaps I'm mistaken - I always assumed the idea was it could be used to make the arm in first-person less (or more) 3D, which is what I previously used it for so I'm intrigued.

**Comment by tr7zw** [comment]
Wait, there was a slider like that? Then I flat out forgot about it when implementing the new rendering.
