### ISSUE TITLE
Add config for head voxel size

### ISSUE THREAD

**Issue by tr7zw** [tr7zw/3d-Skin-Layers#2]
Current size is incompatible with for example villager hats.

**Comment by vos6434** [comment]
could you add a 3D toggle for each body part?

**Comment by tr7zw** [comment]
> 
> 
> could you add a 3D toggle for each body part?

More exact than head and everything else? When would you like 3D arms but 2d legs^^?

**Comment by vos6434** [comment]
With my skin I don't like the 3D layer for the head but I love it for the rest of my body.

**Comment by honchokomodo** [comment]
please extend this a bit and add config options for scaling of each body part's voxel size

i think most of the mismatched pixel problems could be fixed by fiddling around with the scaling/translation

**Comment by tr7zw** [comment]
> i think most of the mismatched pixel problems could be fixed by fiddling around with the scaling/translation

From the readme/curse:
> Just keep in mind that the outer skin layer is slightly bigger than the main player model, so the cubes will not line up perfectly with the skin.

the outer layer is x% bigger than the inner layer with the same amount of pixels. So the pixels physically can't match the ones bellow. You could forcefully do that, but then it won't line up around corners any more. There is no solution that will work/look good with all possible skins.
