### ISSUE TITLE
[1.1.0 FORGE] For some reason config is not working for me.

### ISSUE THREAD

**Issue by KKotik** [tr7zw/3d-Skin-Layers#20]
![image](https://user-images.githubusercontent.com/45950781/141529716-7e8021de-5ca7-4255-9deb-a6becff00b53.png)
There is a bug I am getting, to fix that I am editing config files and even disabling 3D layer for head is doing nothing for me.

**Comment by tr7zw** [comment]
The file won't auto-reload. You can access the config in-game on forge if you have https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption.

**Comment by KKotik** [comment]
It even not working after rebooting the game. This is the issue.
Also I have almost same mod for configurating mods directly from the game called Configurated, and even it can't detect working config for this version. I am on 1.16.5 and latest forge version. With all mods updated.

**Comment by tr7zw** [comment]
Then try to use the config menu accessible via the main menu mod list. I don't know Configurated, so can't tell you why it might not detect a normal config screen.

**Comment by tr7zw** [comment]
Any update?

**Comment by KKotik** [comment]
I was trying to initiate an issue again across the whole december, and it is randomly disappeared. I think that issue is closed. Thanks for help.
