### ISSUE TITLE
An error occurred while rendering the player

### ISSUE THREAD

**Issue by 7yudinglaopin8** [tr7zw/3d-Skin-Layers#201]
I have no idea what the cause of the problem is.
crash-reports:
[crash-2024-11-17_23.29.38-client.txt](https://github.com/user-attachments/files/17791131/crash-2024-11-17_23.29.38-client.txt)
This question usually arises when you first enter the world.

**Comment by tr7zw** [comment]
> SINYTRA CONNECTOR IS PRESENT!
Please verify issues are not caused by Connector before reporting them to mod authors.

Will not be checked as your setup is not supported. Also, this seems to be related to some Essential logic, unrelated to 3d skin layers itself.
