### ISSUE TITLE
[Bug] 1.21.4-fabric crashes when rendering a mob head

### ISSUE THREAD

**Issue by imSarahOwl** [tr7zw/3d-Skin-Layers#203]
I was trying to compile the 1.21.4 fabric branch, and I discovered a crash with rendering some mob heads

**Steps to reproduce**

- Compile mod to 1.21.4
- Open your inventory and try to get a mob head

**Additional info**

The issue only seems to happen when rendering the mob head item, the block renders normally

**Logs**

[crash-2024-12-04_19.20.54-client.txt](https://github.com/user-attachments/files/18014935/crash-2024-12-04_19.20.54-client.txt)
[latest.log](https://github.com/user-attachments/files/18014942/latest.log)

I apologize if the bug report/issue isn't the best, I'm a new dev and this is my first bug report

**Comment by R00tB33rMan** [comment]
@tr7zw, your latest release still, unfortunately, contains this issue.

**Comment by tr7zw** [comment]
Honestly didn't see that ticket in time. With mob head stuff do you mean like zombie heads?

**Comment by imSarahOwl** [comment]
Yes, I tested it with zombie and skeleton heads, but just rendering the item is enough to crash the game

**Comment by allorionmusic** [comment]
Happens with me too! I had a dragon head in my chest and every time I tried to open it, it crashes
