### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by coderbot16** [tr7zw/3d-Skin-Layers#23]
SkinUtil calls `NativeImage#untrack()`, seemingly in an attempt to deallocate the NativeImage object: https://github.com/tr7zw/3d-Skin-Layers/blob/9b3cc5f5f04dd886eaf8da32534dc92f30107cd7/3dSkinLayers-Shared/src/main/java/dev/tr7zw/skinlayers/SkinUtil.java#L61

However, `NativeImage#untrack()` does not deallocate the texture - rather, it removes it from LWJGL's leak tracking, meaning that not only does this code potentially leak memory, it does so in a way that is invisible to LWJGL's debugging tools.

It seems like you intended to call `NativeImage#close()`.

**Comment by tr7zw** [comment]
Thanks for that info. That's quite an unfortunate name, I'll fix it across my projects.

**Comment by coderbot16** [comment]
You're welcome, and yeah, I wish the name were a little more indicative of what it does, maybe it would be nicer if it were named `NativeImage#leakSilently()` instead.

**Comment by tr7zw** [comment]
In the end it leaks 1-5kb of memory(once per loaded player), so I doubt anyone managed to crash their game with this yet, but still better to fix this^^.
