### ISSUE TITLE
Certain faces don't tint red when taking damage

### ISSUE THREAD

**Issue by Khodyn** [tr7zw/3d-Skin-Layers#26]
broke my legs to report this bug :(
![image](https://user-images.githubusercontent.com/49518050/144538551-3c46c7c7-936a-414a-9f3e-d244ba0be322.png)
Normal:
![image](https://user-images.githubusercontent.com/49518050/144538650-285f74c1-b925-4943-b083-b0bc67673c7b.png)

**Comment by tr7zw** [comment]
They do tint, just incorrectly(just color shift to red, so black stays black). This is a workaround because the correct "dmg glow" doesn't work correctly for whatever reason. So currently a won't fix till someone figures out why this is the case.
