### ISSUE TITLE
Using left hand as main hand in first person looks strange (+1 other *slight* discomfort)

### ISSUE THREAD

**Issue by agent7c** [tr7zw/3d-Skin-Layers#27]
I have recently switched to using my left hand as the main hand in Minecraft. This is all handy-dandy until I realised that disabling the first-person skin model reveals an offset outer layer, as shown here: 
![image](https://user-images.githubusercontent.com/95990286/145698016-8c3e4c2b-b240-49be-b9b0-235ef348e023.png)
It is **not a skin issue** (for reference, pictures of my skin are posted at the bottom)
Sure, it's only annoying to left-preferring players and wouldn't ever be that high-priority but it's something that's very easily overlooked.
Also, while writing this, I discovered that the first-person hands also don't reflect the skin customisation options; I had all my outer layers except for hat turned off. Still not any major bug that needs to be fixed or anything.
Left hand (with markings):
![image](https://user-images.githubusercontent.com/95990286/145698199-2df273bf-0bb9-47a2-8a96-5294ebd6ffc0.png)
Even Right hand (with markings):
![image](https://user-images.githubusercontent.com/95990286/145698239-8ffbca2f-02bd-444b-9483-43a5af6b971b.png)
**I am using other mods** but they wouldn't affect the player model in any way.
Fix in your own time, *no rush.*

My skin (visualised on minecraftskinstealer.com):
![image](https://user-images.githubusercontent.com/95990286/145698418-4d89698c-30b5-46ea-abf4-3ad83abcf2a8.png)
![image](https://user-images.githubusercontent.com/95990286/145698423-512423e6-a6d1-423a-8cae-5bcc5d2593af.png)
![image](https://user-images.githubusercontent.com/95990286/145698434-d5c690bd-733a-486c-b8ce-858d7a48a2a3.png)
In MC using this mod:
![image](https://user-images.githubusercontent.com/95990286/145698451-65ac6fd9-cc12-4b96-92af-5bdc173d0097.png)
![image](https://user-images.githubusercontent.com/95990286/145698472-34c27223-432e-46a9-94b9-56fc82b4b0d8.png)

**Comment by tr7zw** [comment]
Fixed the left hand in the next update.
