### ISSUE TITLE
[Issue] My mod disable the animation.

### ISSUE THREAD

**Issue by Taknax** [tr7zw/3d-Skin-Layers#29]
I have mod called TaxSkinForcer [https://www.curseforge.com/minecraft/mc-mods/taxskinforcer](url). I would like to combine it with 3dSK in my modpack, but it is sadly disabling the animation and the normal skin gets rendered. I beg you to make a compatiblity and hope it is even possible. I tried myself but my exp wasnt enough to handle a compatiblity. I really enjoy your mods.

**Comment by Taknax** [comment]
Animation was the wrong word i am sorry. I meaned that the second layer dont render, if i combine the both mods.

**Comment by tr7zw** [comment]
Check with the newest version, I did some more logic rework that might fix this.
