### ISSUE TITLE
[Bug] When Bow fix is enabled in notenoughanimations, when having an offhand charged crossbow, the other hand corrupts

### ISSUE THREAD

**Issue by RaptaG** [tr7zw/3d-Skin-Layers#30]
Title

**Comment by tr7zw** [comment]
Ah crap I remember this happened on Last Life actually. Will be fixing this in the next release.

**Comment by tr7zw** [comment]
Wait, this is on the wrong repo? That was fully just Not enough animations and nothing to do with this mod?

**Comment by RaptaG** [comment]
No, I mean that the 3D render of the other hand corrupts, it has to do with 3D Skin Layers

**Comment by tr7zw** [comment]
Ahhh ok then it's the same issue as with the head on a ladder. Noted, will look into it.

**Comment by RaptaG** [comment]
Glad to help! :)

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/153031600-af930c31-f5c4-4694-960e-ad4424224638.png)
Looks fine to me? To be fair, the recent update seems to have fixed some other issues with not enough animations too, like the head layer on ladders.

**Comment by RaptaG** [comment]
It was my bad from the begging for not providing a screenshot..
That's the actual issue (check the right hand):

![2022-02-08_22 00 45](https://user-images.githubusercontent.com/77157639/153066622-bd5bf670-18f0-4b46-8de8-60d512a23c9b.png)

**Comment by tr7zw** [comment]
And what exactly is with the screenshot? I mean the arm and layers seem to be in the normal location?

**Comment by RaptaG** [comment]
That's how my hand actually looks:

![2022-02-08_22 08 09](https://user-images.githubusercontent.com/77157639/153069347-4e676086-9d57-4188-89b3-4c7f59a83361.png)

**Comment by tr7zw** [comment]
Confirmed a vanilla bug, so unrelated to 3d Skin Layers (or not enough animations).
