### ISSUE TITLE
Make it for 1.12.2

### ISSUE THREAD

**Issue by zigordlc** [tr7zw/3d-Skin-Layers#33]
I just saw that you made a 1.8.9 version of your awesome mod, could you make it for 1.12.2 too? It would be cool, since a lot of people use this version to play with mods, and stuff. Thx

**Comment by tr7zw** [comment]
Honestly, I'll need a week or two to recover from working with legacy versions for now.
A 1.12 port is planned *someday*, but for now, other mods/updates have priority.

**Comment by zigordlc** [comment]
Yeah, no problem. I just wanted to know if you had plans on porting it to 1.12 someday, my skin looks awesome with your mod. Thank you for responding!
