### ISSUE TITLE
Enhance : add support for 1.8

### ISSUE THREAD

**Issue by HowardZHY** [tr7zw/3d-Skin-Layers#35]
Could you make the 1.8.9 version also compatible with 1.8? I would be really appreciate if it works on 1.8. 
[crash-2022-02-12_00.27.34-client.txt](https://github.com/tr7zw/3d-Skin-Layers/files/8050209/crash-2022-02-12_00.27.34-client.txt)

**Comment by tr7zw** [comment]
Sorry but 1.8.0 should never never never never never be used. Always only 1.8.9/1.8.8.
