### ISSUE TITLE
Graphic issues with Origins 

### ISSUE THREAD

**Issue by Estrelaura** [tr7zw/3d-Skin-Layers#36]
The Origins mod changes the player model under some circunstances, making it translucent and/or tinted. 3D Layers are unaffected by that.

**Comment by tr7zw** [comment]
The layers work in the same context as other RenderLayers(Like the cape/held items/arrows stuck in the player/parrot on shoulder), so other effects like the red tint on damage also technically don't work correctly(currently using some color changes to simulate it). Any help on how to get the layers into the same render context as the skin, so effects like tint/translucency apply to it too, is appreciated. One idea could be to move the entire render logic with mixins into the player model rendering, but that might have a negative impact on mod compatibility(?).

**Comment by tr7zw** [comment]
I think this issue doesn't apply anymore, as the correct rendering is now used.
