### ISSUE TITLE
Crash between latest Sodium and 3d skin layers with Block Entity (Skeleton Skull)

### ISSUE THREAD

**Issue by LunexLunertic** [tr7zw/3d-Skin-Layers#37]
Version information:

3dSkinLayers-Fabric-mc1.18-1.4.0
sodium-fabric-mc1.18.2-0.4.1+build.15

Reproduction Steps
1: Make nether portal
2: fly around the nether (or overworld), go to a chunk which has data to generate a structure that has any block entity with a skeleton skull (requires a structure datapack or structure mod since they do not generate naturally, this case being Repurposed Structures and its included required dependency)
3: crash

Here's the crash report and log:
[crash-2022-03-03_09.44.22-client.txt](https://github.com/tr7zw/3d-Skin-Layers/files/8179902/crash-2022-03-03_09.44.22-client.txt)
[latest.log](https://github.com/tr7zw/3d-Skin-Layers/files/8179904/latest.log)

**Comment by tr7zw** [comment]
Nothing in the crash log points to this mod, also thats 1.18.2, for which this mod wasn't yet tested/compiled^^

**Comment by LunexLunertic** [comment]
You are correct, I simply await for your mod to update since I was shown by the Sodium dev as to what coding was causing the problem but I should be aware the coding within Minecraft has been changed for 1.18.2, thank you.

**Comment by tr7zw** [comment]
``NoSuchMethodError: 'double net.minecraft.class_2338.method_10268(double, double, double, boolean)'`` that could only happen due to something not matching up between 1.18.1 and 1.18.2, so at least a compile against 1.18.2 is required, potentially also code changes.

**Comment by LunexLunertic** [comment]
Oh yes, here's the comment from the sodium dev which points to what line it is to help you out:

https://github.com/CaffeineMC/sodium-fabric/issues/1204#issuecomment-1058333144

Anyways I'll look forward to the update, I gotta have patience after all, take your time.
