### ISSUE TITLE
Feature Request: MCXR Support

### ISSUE THREAD

**Issue by BloxBoss6** [tr7zw/3d-Skin-Layers#40]
I play Questcraft on my oculus and your mod runs on it by default with fabric. When you go to settings or look into the inventory, the 3d skin layers are working. The issue is that it doesn't work with the hands that are used for your controllers. I was wondering if you could add support as you did for First Person Mod which also kind of works in VR. If this isn't possible I understand completely.

Thanks!

**Comment by tr7zw** [comment]
Huh there is a VR version for the quest, I only knew about Vivecraft. There seem to be a few issues: Questcraft is closed source from what I can tell, and I only own a Oculus Rift CV1, so I couldn't test it. I guess the arms used for the controllers work like with Vivecraft, not being the actual models arms(and thats why this mod doesn't work for it). I don't think there is much that I can do about this.

**Comment by BloxBoss6** [comment]
Well from what I can tell Questcraft is more accurately a modpack and launcher than a mod itself. They probably do some changes to it, but the general mod that adds the VR capabilities is MCXR, which is a Fabric mod for VR. I might be wrong, but that's what I've gathered from videos and the discord.

[MCXR Github](https://github.com/Sorenon/MCXR)

**Comment by tr7zw** [comment]
There is a non Vivecraft, fabric compatible vr mod?!? Well, guess time to setup my Rift again...

**Comment by BloxBoss6** [comment]
Oh and here is the link for the Questcraft GitHub. It's a bunch of repositories all used by it if that helps.

[Link](https://github.com/QuestCraftPlusPlus)

Thanks for looking into this!

**Comment by tr7zw** [comment]
Well since I dont have a Quest, I'll just assume that fixing it on PC will fix it there too. Currently more hyped that MCXR is a thing at all, because Vivecrafts codebase is a pain in the ass and will never work on Fabric/with Sodium+Iris.

**Comment by tr7zw** [comment]
Ah yea, got it working after a lot of issues with oculus not detecting the USB devices, this is great. Worked with all my installed mods except Blur. I'll look into making all my mods as seamless as possible.

**Comment by tr7zw** [comment]
No I mean the entire thing at all worked after a few hours. Like VR^^ The arm won't have the layers for now till it has some API or some other trickery.

**Comment by BloxBoss6** [comment]
Cool, That's what I thought. Thanks again for looking into this!

**Comment by tr7zw** [comment]
MCXR is not a thing anymore from what I know, so closing this issue. There is an API now to get the 3d models for rendering, so if the project gets picked up again, that would be doable.
