### ISSUE TITLE
Latest forge version has possibly wrong version tags

### ISSUE THREAD

**Issue by Warhand** [tr7zw/3d-Skin-Layers#41]
The latest forge version on curseforge has version tags for both 1.18.1 and 1.18.2, however the file name only includes 1.18.2, I'm unsure if this is an error, or if the file supports both versions of the game, but I figured it wouldn't hurt to mention in case its the former.

**Comment by tr7zw** [comment]
Nope it's intentional. The version in the filename is just what was used in development. But all my mods fork for 1.18.0-1.18.2 with the same jar. Not sure why so many ppl look at the jar filename, not at the list of supported versions.

**Comment by Warhand** [comment]
Its mostly because sometimes devs mislabel versions on curseforge
