### ISSUE TITLE
Emissive on Elytras Overwritten by 3D skin layers 

### ISSUE THREAD

**Issue by Lucipo** [tr7zw/3d-Skin-Layers#42]
![image](https://user-images.githubusercontent.com/36358294/160245348-e4977c74-c786-4763-b215-6daa44287648.png)

Any Pixels on a skin's 2nd layer when using the Entity Texture Features mod ( https://github.com/Traben-0/Entity_Texture_Features )
will show over the emissive particles on an elytra, even when the elytra is infront of the secondary skin layer. Predicted this is to do with beacons not showing over the second layer of skins when in F5 or for other players.

Am Using latest version of fabric and both ETF and Skin Layers 3D on 1.18.1. Also using CITResewn to allow CIT on clients without optifine's functionality.

**Comment by tr7zw** [comment]
Eh stacked transparency is a common mc rendering issue. Sodium currently works on including a fix.

**Comment by Traben-0** [comment]
This issue was resolved a few months back on ETF's end

**Comment by tr7zw** [comment]
Got it!
