### ISSUE TITLE
Second layer of arm still visible in first person

### ISSUE THREAD

**Issue by McSquizzleswag** [tr7zw/3d-Skin-Layers#49]
I'm using the latest version available for 1.18.1: 3dskinlayers-forge-1.4.3-mc1.18.2.jar, I have the second layer of my skin disabled but when in first person the second layer of the arm is still visible, in third person it isn't there, without the mod it works as it should
![Base Profile Screenshot 2022 04 16 - 13 14 24 66](https://user-images.githubusercontent.com/36580881/163684856-72966013-38b6-40f9-b262-975663aaef2a.png)
![Base Profile Screenshot 2022 04 16 - 13 14 31 10](https://user-images.githubusercontent.com/36580881/163684866-e8a90ede-234e-43a6-a0ea-6a268c9862c3.png)

**Comment by tr7zw** [comment]
Uhhhh huh. Looks like a missing check, will be fixed in the next release.
