### ISSUE TITLE
Some items when worn in the head make the 3d layer not show

### ISSUE THREAD

**Issue by Viruzaum** [tr7zw/3d-Skin-Layers#5]
Some items like banner or torches make the 3d layer on the head not show up and make me bald.

With nothing
![javaw_zysaKzraGQ](https://user-images.githubusercontent.com/23330390/131525200-01c6b0c1-78a0-4949-96e9-158e64523608.png)

With banner
![javaw_5INJTGyEry](https://user-images.githubusercontent.com/23330390/131525252-ac0fc187-dff6-4c76-9036-4fc178fb1b2a.png)

With torch
![javaw_6ACDPRTAfv](https://user-images.githubusercontent.com/23330390/131525459-1a55a479-cf12-478f-8ca9-66382fa4dbb3.png)

Other items seem to work fine (have not tested all)
![javaw_JfDFXU1DVn](https://user-images.githubusercontent.com/23330390/131525381-75df7cfb-00a8-4a71-9ac6-70c4e7effc09.png)

**Comment by tr7zw** [comment]
It hides the head layer when a block is worn because of pumpkins. But I guess it filters a bit too much.

**Comment by tr7zw** [comment]
Ah the issue where player heads, where the 3d layers do poke through. Gonna limit it to that.
