### ISSUE TITLE
For some reason, 1.18.2 Forge isn't working (skin doesn't appear in 3D)

### ISSUE THREAD

**Issue by Desempregago** [tr7zw/3d-Skin-Layers#51]
![2022-04-17_15 49 10](https://user-images.githubusercontent.com/14002834/163728316-fb5b9e60-36ed-499f-aeae-dda91787b21b.png)

You can see it in the arms and part of the legs

Mod List
![image](https://user-images.githubusercontent.com/14002834/163728343-b31e5eaf-4046-4d51-b797-485705e432e6.png)

**Comment by tr7zw** [comment]
TLauncher and others that allow you to play the game without buying it(and still having a skin) are not supported.

**Comment by Desempregago** [comment]
I'm not using TLauncher

**Comment by tr7zw** [comment]
You are using Offline Skins.

**Comment by Desempregago** [comment]
![image](https://user-images.githubusercontent.com/14002834/163728465-bf26e670-320c-4b28-8c5c-e63fbcdf6fdc.png)

**Comment by Desempregago** [comment]
Some people I play with use cracked launchers, but they complain that their skins doesn't show, so I use OfflineSkins for them

**Comment by Desempregago** [comment]
so is OfflineSkins the culprit then?

**Comment by tr7zw** [comment]
It's possible that I've accidentally fixed it in the next release/current snapshot build(downloadable in the Actions tab here on Github). If not, I'll not look into fixing it, since it does violate Mojangs Terms of Service.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/3d-Skin-Layers/actions/runs/2180295740 in the Artifacts file is a forge/fabric build for 1.18.x. Give it a try, maybe it works.

**Comment by Desempregago** [comment]
You don't need to risk ToS breakage, I just wanted to know why it happened. Don't worry too much about it, it's probably like a bad mod interaction caused by OfflineSkins.
