### ISSUE TITLE
1.12.2 Render Problem of Shoulders and 1 Question of the Changelog and 1 Question of a Crash Report for compatibility with other Mods

### ISSUE THREAD

**Issue by Titoo8899** [tr7zw/3d-Skin-Layers#54]
Hi,
I have Played the new 1.12.2 Mod Version of your mod played and have a Problem with the Rendering of the Shoulders found. Then you look the 2 Pictures you see the Shoulders Render not correct of the Point and you can look with a small gap behind this or you see the colours of the Head then you look for 100%. And yes the Rendering Problem is mini but I find it is a area who many Player looks and see this. I hope you can with this 2 Pictures a Fix for this Rendering Problem make.

One of the 2 Questions what I have is for the Settings in your Mod. You have in your Changelog for the 1.12.2 Minecraft Version write:
"- No ingame settings screen(you can use 1.16+ settings files)"
The Question is what mean you with "1.16+ settings files" and who found I this and give it a way to make the Ingame Setting menu of the 1.18.2 for 1.12.2?

And the other Question is. I have a Crash Report and this world was Crash as I have other Mods with your Mod play. I have load the world and then was Minecraft Crash. Can you say me is this Crash from your mod or from a other mod. You have write incompatible Mods and I have no idear what the Crash have make. I hope the Crash Report help you to give me a Feedback what it has triggered.
![2022-04-21_18 07 43](https://user-images.githubusercontent.com/42325138/164522750-861f9a7e-0a03-45a5-835f-bbdc66e01b72.png)
![2022-04-21_18 07 53](https://user-images.githubusercontent.com/42325138/164522758-7f758918-d400-46c3-8bab-f518254e36f3.png)

**Comment by Titoo8899** [comment]
Crash Report for Help you for Question 2:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Custom Hand Gui mod (customgui-1.12.2-1.4.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.1.jar)
  Fluidlogged API Plugin (Fluidlogged-API-v1.7.2b-mc1.12.2.jar)
  SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.16a-mc1.12.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 4/21/22 6:05 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.fexcraft.mod.fvtm.sys.uni.SystemManager.onWorldUnload(SystemManager.java:149)
	at net.fexcraft.mod.fvtm.util.Resources.onWorldUnload(Resources.java:854)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_151_Resources_onWorldUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2435)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2430)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147231_a(NetHandlerPlayClient.java:784)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:354)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1724)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fexcraft.mod.fvtm.sys.uni.SystemManager.onWorldUnload(SystemManager.java:149)
	at net.fexcraft.mod.fvtm.util.Resources.onWorldUnload(Resources.java:854)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_151_Resources_onWorldUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2435)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2430)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147231_a(NetHandlerPlayClient.java:784)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:354)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Titoo8899'/112, l='MpServer', x=-1079.80, y=4.00, z=40.89]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1093,4,48), Chunk: (at 11,0,0 in -69,3; contains blocks -1104,0,48 to -1089,255,63), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Level time: 217005 game time, 1391 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Titoo8899'/112, l='MpServer', x=-1079.80, y=4.00, z=40.89]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 444456560 bytes (423 MB) / 1409286144 bytes (1344 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version        | Source                                     | Signature                                |
	|:------ |:------------------------ |:-------------- |:------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2         | minecraft.jar                              | None                                     |
	| LCHIJA | mcp                      | 9.42           | minecraft.jar                              | None                                     |
	| LCHIJA | FML                      | 8.0.99.99      | forge-1.12.2-14.23.5.2860.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2860   | forge-1.12.2-14.23.5.2860.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | skinlayers               | 1.1.0          | 3dSkinLayers-forge-mc1.12.2-1.1.0.jar      | None                                     |
	| LCHIJA | securitycraft            | v1.9.1         | [1.12.2]+SecurityCraft+v1.9.1.jar          | None                                     |
	| LCHIJA | fcl                      | 1.12.74        | Fexcraft+Common+Library-1.12.74.jar        | None                                     |
	| LCHIJA | scm                      | 1.1.00         | CDM-v1.12.2-1.1.00.jar                     | None                                     |
	| LCHIJA | customgui                | 1.4            | customgui-1.12.2-1.4.jar                   | None                                     |
	| LCHIJA | supermartijn642configlib | 1.0.9a         | supermartijn642configlib-1.0.9a-mc1.12.jar | None                                     |
	| LCHIJA | durabilitytooltip        | 1.1.0          | durabilitytooltip-1.1.0-mc1.12.jar         | None                                     |
	| LCHIJA | ebb                      | 1.0.0          | ElytraBombing-Forge-1.12.2-1.0.0.jar       | None                                     |
	| LCHIJA | exw                      | 1.1.0          | Expansive+Weaponry-1.1.0.jar               | 1c16a04cf2de02e4ee45d4c16af7e51af2d45c4d |
	| LCHIJA | externalview             | 2.0            | ExternalView-2.0.jar                       | None                                     |
	| LCHIJA | fancyclear               | 1.0            | FancyClear-Forge-1.12.2-1.3.1.1.jar        | None                                     |
	| LCHIJA | frl                      | 1.0            | Fexcraft+Common+Library-1.12.74.jar        | None                                     |
	| LCHIJA | tmt                      | 1.14           | Fexcraft+Common+Library-1.12.74.jar        | None                                     |
	| LCHIJA | fishingmadebetter        | 2.2.2          | FishingMadeBetter-1.12.2-2.2.2.jar         | None                                     |
	| LCHIJA | fluidlogged_api          | 1.7.2b         | Fluidlogged-API-v1.7.2b-mc1.12.2.jar       | None                                     |
	| LCHIJA | creatures                | 1.0            | frikinzis-fauna-1.3.0-1.12.2.jar           | None                                     |
	| LCHIJA | fvtm                     | 3.7.62         | FVTM-3.7.63.jar                            | None                                     |
	| LCHIJA | geckolib3                | 3.0.20         | geckolib-forge-1.12.2-3.0.21.jar           | None                                     |
	| LCHIJA | mts                      | 21.1.0         | Immersive+Vehicles-1.12.2-21.1.0.jar       | None                                     |
	| LCHIJA | djumpplates              | 1.1            | JumpPlates-1.12.2-1.1.jar                  | None                                     |
	| LCHIJA | guilib                   | $version       | morepaintings-paintings-1.12.2-5.0.1.2.jar | None                                     |
	| LCHIJA | paintingselgui           | $version       | morepaintings-paintings-1.12.2-5.0.1.2.jar | None                                     |
	| LCHIJA | morepaintings            | $version       | morepaintings-paintings-1.12.2-5.0.1.2.jar | None                                     |
	| LCHIJA | supermartijn642corelib   | 1.0.16a        | supermartijn642corelib-1.0.16a-mc1.12.jar  | None                                     |
	| LCHIJA | movingelevators          | 1.3.4          | movingelevators-1.3.4-mc1.12.jar           | None                                     |
	| LCHIJA | orva_alarms              | 2.3            | Orva+Alarms+2.3+1.12.2.jar                 | None                                     |
	| LCHIJA | parkour_recorder         | 1.1.2.0-1.12.2 | parkour_recorder-1.1.2.0-1.12.2.jar        | None                                     |
	| LCHIJA | railways                 | 1.0            | SugarLight-1.0.jar                         | None                                     |

	Loaded coremods (and transformers): 
Custom Hand Gui mod (customgui-1.12.2-1.4.jar)
  
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.1.jar)
  
Fluidlogged API Plugin (Fluidlogged-API-v1.7.2b-mc1.12.2.jar)
  git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.16a-mc1.12.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Expansive Weaponry v1.1.0 (1.1.0): 
	States: 'U' = Unloaded 'L' = Loaded 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID  | Version | Source                                | Type                     |
	|:----- |:--- |:------- |:------------------------------------- |:------------------------ |
	| ULA   | cf  | 1.0.2   | Modern Warfare-Content Pack-1.0.4.jar | EXPANSIVE_WEAPONRY : exw |
	| ULA   | omw | 1.0.0   | OMW-Content Pack-1.0.1.jar            | EXPANSIVE_WEAPONRY : exw |

	
	FVTM Addons: 
	| fvtm | FVTM [Internal Addon] | 3.7.62 | ...:\Users\Mirko PC\AppData\Roaming\.minecraft\mods\FVTM-3.7.63.jar|
	| gsp  | Generic Signs Pack    | 1.0.0  | ...C:\Users\Mirko PC\AppData\Roaming\.minecraft\mods\GSP.jar    |

	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.15, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by tr7zw** [comment]
The 2 images look like the head is clipping through the shoulders? Could also be that your skin has pixel there that is transparent, but only 99% transparent. Then it gets turned into a cube, that looks like there is a hole.
To the config: Like it says, if you want to customize for example the cube sizes, the current way to do it is to use 1.18(-1.16) and change the settings in the menu, then copy over the config file. 1.8 and 1.12 are horrible to mod for, so I currently don't plan to backport the config GUI. Too much spaghetti code that Mojang created there.
The crash seems to be ``net.fexcraft.mod.fvtm`` (https://github.com/Fexcraft/FVTM). I think it's unrelated.

**Comment by Titoo8899** [comment]
I have the Owner from FVTM write and now hope he find the Problem of her Mod.

**Comment by Titoo8899** [comment]
And with the settings in the menu okay it is many many time so what to create and the functions to write but I hope so much for a Update in the future from you with a Setting in the menu for the 1.12.2 version

**Comment by Titoo8899** [comment]
Have my skin edit and have ghost pixels of the Skin Edit and now rendert it better.

**Comment by tr7zw** [comment]
I guess this means all 3 things are fixed 👍
