### ISSUE TITLE
[1.1.0][Forge] Duplicated Mod Id: File name

### ISSUE THREAD

**Issue by jlucaso1** [tr7zw/3d-Skin-Layers#55]
I'm facing problems running this mod both together with others and alone.
![unknown](https://user-images.githubusercontent.com/55464917/164915121-2e5126a3-2f1b-406a-a483-04e264527103.png)

modlist: 3dSkinLayers-forge-mc1.12.2-1.1.0.jar
forge version: 14.23.5.2860
minecraft version: 1.12.2

**Comment by tr7zw** [comment]
Looks like you have installed the jar twice?

**Comment by jlucaso1** [comment]
> 

No.
My mods folder:
![image](https://user-images.githubusercontent.com/55464917/164936165-321aa0c7-60d3-4825-8f4c-620e23fe0b68.png)

**Comment by tr7zw** [comment]
Then I have no clue what happened here? I need the latest.log so I can see what the hell forge is doing.

**Comment by Depressomane** [comment]
https://pastebin.com/f9JWv2qH

This issue is still happening, sorry for Necroing but it seems a solution was never published for 1.12.

**Comment by tr7zw** [comment]
This was never resolved. I closed this due to inactivity and no one else reporting it, and not even having a log. Your log points more to this: 

> [12:09:06] [Client thread/ERROR]: There was a problem reading the entry org/spongepowered/asm/launch/MixinLaunchPlugin.class in the jar C:\Users\johnt\AppData\Roaming\gdlauncher_next\instances\CarlCraft-II\..\..\instances\CarlCraft-II\mods\3dSkinLayers-forge-mc1.12.2-1.2.0.jar - probably a corrupt zip

**Comment by mahoroa70** [comment]
[latest.log](https://github.com/tr7zw/3d-Skin-Layers/files/13344730/latest.log)
I'm an outsider, so please excuse me.
This mod minecraft1.12.2
forge14.23.5.2860
The same bug was confirmed when I used it alone, so I will attach the log.
I would appreciate it if you could check it out.

※
I'm using Google Translate, so it may not be accurate English.
sorry.

**Comment by tr7zw** [comment]
As said above, I have no clue why that error is happening, its some kind of 1.12 issue in relation with mixins. I don't have the time or motivation to look into this, as I'm not interested in 1.12(the 1.12 version of this mod was more an experiement, and has been outdated for a long time) and currently really busy with irl stuff, so I can barely keep the current mods updated, let alone spare time to look into edge case issues with old versions.

**Comment by Nikiroy78** [comment]
I encountered this error when writing my launcher. Everything works on a third-party launcher. Maybe minecraft should be launched with some additional arguments? Maybe the accuracy of the --uid and --accessToken arguments still affects the stability of the mod. Please indicate this to the author.

**Comment by Nikiroy78** [comment]
In general, I decided to check the logs here, I see:
```
[00:29:05] [ Client thread/FATAL] [FML]: Found a duplicate mod skin layers 3d at [W:\projects\untracked\launcher\binaries-win32\minecraft\mods\3dSkinLayers .jar, binaries-win32\minecraft\mods\3dSkinLayers.jar]
```
I previously had a relative file path in my arguments. not a complete one. @jlucaso1, @mahoroa70, double-check the arguments with which you run minecraft.

@tr7zw, of course, no one has contacted you with these, because they use normal launchers that know how to correctly register the paths to the game folders

**Comment by tr7zw** [comment]
Ah I mean, yea. If you somehow double-add the mods folder to the path, that might mess stuff up.

**Comment by Nikiroy78** [comment]
No, it’s even cooler: the relative path to the game folder was indicated there, but you need to use the full one, otherwise Minecraft will complain about two identical files.
Bottom line: let them double-check the program arguments for relative paths, not full ones.

(Sorry, English is not my native language, I use a translator)
