### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by Sanadriell** [tr7zw/3d-Skin-Layers#56]
pt_br

https://gist.github.com/Sanadriell/0be504468c0dc16e4b596a460062e13b

**Comment by tr7zw** [comment]
Looks good, will check and add them next update. (Just did one ~2 hours ago, so might take a bit)

**Comment by Sanadriell** [comment]
> Looks good, will check and add them next update. (Just did one ~2 hours ago, so might take a bit)

Sure
Thank you
