### ISSUE TITLE
About sharing

### ISSUE THREAD

**Issue by MrXiaoM** [tr7zw/3d-Skin-Layers#57]
Hello there. It is a nice Mod. May I post it to a Chinese Minecraft forum (www.mcbbs.net)? I will keep your CurseForge link, ko-fi link, etc in the post. And there is no attachments going to be uploaded. The download link will be redirected to your CurseForge link.

**Comment by tr7zw** [comment]
Of cause that's fine. If the file would be reuploaded there I'd have to take a closer look, but if it's just linking to the CurseForge download that's absolutely fine. Also saw the translation PR, will give it a rough check with Google Translate to see that it looks right and then merge it into the next releases.
