### ISSUE TITLE
[question]1.8.9 hs-err

### ISSUE THREAD

**Issue by HowardZHY** [tr7zw/3d-Skin-Layers#59]
[hs_err_pid9700.log](https://github.com/tr7zw/3d-Skin-Layers/files/8663115/hs_err_pid9700.log)
is this related with 3d skin layers ?

**Comment by tr7zw** [comment]
Hm the 1.8.9/1.12 versions have to grab the skin from the gpu, and for that have to assume its 64x64. My guess is that you use a texture pack where the steve/alex skin are higher res than that, causing this crash.

**Comment by tr7zw** [comment]
Then don't load hd skins.

**Comment by HowardZHY** [comment]
I think a test with only CSL mod is needed

**Comment by tr7zw** [comment]
This will happen if a player has a skin that is not 64x64(no matter how it is loaded, Resourcepack/Custom Skin Loader etc).

**Comment by HowardZHY** [comment]
[hs_err_pid7876.log](https://github.com/tr7zw/3d-Skin-Layers/files/8663364/hs_err_pid7876.log)
csl 128x skin's hserr is differ from that one
jvm.dll =\ ig8icd64.dll

**Comment by tr7zw** [comment]
Doesn't change the fact that hd skins wont work.

**Comment by Lolol4572** [comment]
Why do HD skins never work?
