### ISSUE TITLE
Jacket layer clips with leggings

### ISSUE THREAD

**Issue by Hibiii** [tr7zw/3d-Skin-Layers#6]
Steps to reproduce

1. Have a skin which jacket layer intersects with the top part of leggings
2. Wear leggings in game with no chestplate

This bug might also affect other combinations, like armor textures that are bigger than they're intended (ex.: sleeves and gloves for chestplate). On my skin, the sides of the jacket layer clip with the sides of the leggings.

**Comment by tr7zw** [comment]
The issue is that the body and legs are right next to each other. Now you have the 2nd layer that is bigger around them, so they have to intersect. This is in vanilla too, just less noticeable. I guess the simplest fix is to not have things at the top of the legs/bottom of the body.

**Comment by Hibiii** [comment]
Perhaps  you could just slightly deflate the jacket layer? I like walking around in pants and shoes only and I end up seeing the clipping a lot.

**Comment by tr7zw** [comment]
I'll probably make it a config value, since everyone seems to have different preferences.

**Comment by not-holar** [comment]
Another case of the outer jacket layer being too large (notice the "bowtie" ending up a whole pixel higher than it should be)

![image](https://user-images.githubusercontent.com/58831297/132155061-b95b6c67-435b-41e9-9d77-0ffd7d50806e.png)
![image](https://user-images.githubusercontent.com/58831297/132155072-e43710d4-54cd-472e-84b8-fbb67693f632.png)

**Comment by Khodyn** [comment]
I don't think this mod should even be moving the pixels on the outer layers by default. Ideally it should look just like vanilla, just with geometry added to the sides of pixels. This is an edit of @not-holar 's screenshot to show what I mean:
![3d](https://user-images.githubusercontent.com/49518050/132389183-7b4410c2-26e4-4bdd-a128-6813905993d3.gif)

**Comment by tr7zw** [comment]
Please check the the latest build under Actions, it adds a config where you can change all the settings in that regard.

**Comment by not-holar** [comment]
![image](https://user-images.githubusercontent.com/58831297/132419252-c0ef82f6-3837-493f-a0c4-749841dc86b7.png)
I set all the values to 1.01 and it seems the body and leg layers are indeed both shifted 1 pixel up

**Comment by not-holar** [comment]
![image](https://user-images.githubusercontent.com/58831297/132419450-bc397e18-bde9-46b0-b5f7-edebb4b15e72.png)
The arms aren't quite right either, the layer goes all around the arm in the original

**Comment by tr7zw** [comment]
Yea the arms are tricky because of the 3px/4px arms, so I had to approximate move the entire thing, and guess it's ever so slightly off. And the -= 1 find is a good copy and fail find from the 1.16 src that I just didn't questions^^.

**Comment by tr7zw** [comment]
Hm the offsets needed an update, try now.

**Comment by tr7zw** [comment]
The leg layer might now be a tiiiny bit too low. Maybe I'll move it to the config too.

**Comment by not-holar** [comment]
The offsets look good now, what i think would be wise with the arm layer is to calculate it based on the current voxel size instead of having it as a constant, so that it always remains centered around the arm

**Comment by tr7zw** [comment]
Not really, with the correct offset value for 3/4px arms it should be just correct. The issue is that we are talking about really really small movements to get it to the correct position, so it's just lots of try and error. I hope that for now this is a smaller issue, more important to get out the configs and a Forge build.

**Comment by tr7zw** [comment]
Fixed.
