### ISSUE TITLE
fabric环境下与万用皮肤补丁(CSL)不兼容

### ISSUE THREAD

**Issue by Garan902** [tr7zw/3d-Skin-Layers#61]
如题，版本1.18.2，仅开启这两个mod时，皮肤会变成黑乎乎的，单独运行其中一个时效果正常

**Comment by HowardZHY** [comment]
> I'm unable to find any mod called "Universal Skin Patch", at least that's what trying to translate the title results in. Can you link the mod and add a screenshot of the issue?

He's complaining about with Custom Skin Loader.

**Comment by HowardZHY** [comment]
> 如题，版本1.18.2，仅开启这两个mod时，皮肤会变成黑乎乎的，单独运行其中一个时效果正常

请确认你皮肤的分辨率是64x64
