### ISSUE TITLE
[Bug][1.12.2] Failed to launch with Smart Moving mod (Mixin apply failed)

### ISSUE THREAD

**Issue by HowardZHY** [tr7zw/3d-Skin-Layers#62]
[debug.log](https://github.com/tr7zw/3d-Skin-Layers/files/8735922/debug.log)

[latest.log](https://github.com/tr7zw/3d-Skin-Layers/files/8735923/latest.log)

**Comment by tr7zw** [comment]
Did you perhaps download the build from Github instead of Curse/Modrinth? It's missing the refmap.

**Comment by HowardZHY** [comment]
oh no



At 2022-05-20 22:24:40, "tr7zw" ***@***.***> wrote:

Did you perhaps download the build from Github instead of Curse/Modrinth? It's missing the refmap.

**Comment by tr7zw** [comment]
https://modrinth.com/mod/3dskinlayers/version/1.2.0-forge-1.12.2

**Comment by HowardZHY** [comment]
works fine now
