### ISSUE TITLE
MCAR compatibility

### ISSUE THREAD

**Issue by Dr-WeiAL** [tr7zw/3d-Skin-Layers#63]
If the slender model is selected to enter the game, and the player's arm has double skin, it will be displayed as Classic double skin
![image](https://user-images.githubusercontent.com/47446553/169668861-1486e1f2-6db6-478e-a1b0-884e41ba6bfa.png)
I also posted one here
https://github.com/Luke100000/minecraft-comes-alive/issues/224

**Comment by tr7zw** [comment]
Custom player models can't really be supported. If that mod just changes the player between the alex/steve model, it should also change that in the correct places. https://github.com/tr7zw/3d-Skin-Layers/blob/1.18.2/Shared/src/main/java/dev/tr7zw/skinlayers/mixin/PlayerRendererMixin.java#L68 basically your model internally still reports to have wide arms, so the layers are rendered that way.

**Comment by Dr-WeiAL** [comment]
Uh... let's see what the author of MCA has to say

**Comment by Dr-WeiAL** [comment]
MCAR has solved the compatibility, so close this issue

**Comment by tr7zw** [comment]
Neat.
