### ISSUE TITLE
Incompatible with Essentials mod

### ISSUE THREAD

**Issue by OsoaGH** [tr7zw/3d-Skin-Layers#69]
I think a solution would be disabling 3d layers on parts of the skin which the essentials cosmetics will use as right now, 3d skin layers just overlaps the cosmetics

**Comment by OsoaGH** [comment]
Player is also invisible in game, even with no cosmetics on

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/174457485-661e50f5-a5e4-4d52-86d8-81d6142ccc76.png)
Looks fine to me? Don't have cosmetics to test, but yea if you add something to your skin and then a cosmetic at the same place, they will in fact clip into each other.

**Comment by OsoaGH** [comment]
I believe this was caused by the FabricCapes mod, sorry about that
