### ISSUE TITLE
Compatibility notes

### ISSUE THREAD

**Issue by Alkiasan** [tr7zw/3d-Skin-Layers#7]
Tested with FabricTailor (Mod that allows changing skins). Seems to work.

Surprisingly, works mostly with Figura. Only issue being that Figura models which use the default player model won't load the 3D skin layer at all. Don't know if that is fixable at all...

**Comment by tr7zw** [comment]
Sounds good, I wasn't sure on how it reacts when the players skin changes(depending on the implementation it might keep the old skin layers). And I guess it should be possible to add support for other mods that create custom models, but it might be a bit of a pain in the ass to get working correctly.
