### ISSUE TITLE
Feature request: Compatibility with Wildfire's Gender mod

### ISSUE THREAD

**Issue by HxxThSwggr** [tr7zw/3d-Skin-Layers#71]
[Wildfire's Gender mod](https://github.com/WildfireRomeo/WildfireFemaleGenderMod) adds simple booba with the current skin on them (no custom texture or anything, just two polygons). With 3DSL, the additional chest part of the skin doesn't have a 3D layer, obviously.

I dont know how hard this is to fix, if you want to waste your time on it, or even if you can fix it from your side, but it would be cool.

**Comment by tr7zw** [comment]
Duplicate #14
