### ISSUE TITLE
Yes, you ARE allowed to distribute the binary!

### ISSUE THREAD

**Issue by SkyfallWasTaken** [tr7zw/3d-Skin-Layers#73]
This statement is **false:**

> This license does not allow others to distribute the software/derivative works(in source or binary form). You have to contact the author to get permission for redistribution.

Let's look at the license:

> The Software may not be used to get a) a commercial advantage, or b) monetary
compensation.

A person not working for Rinth Inc. (Modrinth's owner) uploading the mod to something like Modrinth **is** allowed, as there is no commercial advantage, nor is there any monetary compensation.

_disclaimer: IANAL_

**Comment by SkyfallWasTaken** [comment]
In my opinion, you should allow people to distribute the jar, but keep the clause in the license, as I do understand not wanting your mod to be taken advantage of.

**Comment by tr7zw** [comment]
Now let's read the license again:
> this software (in source or binary form) and associated documentation files
(the "Software"), to use, modify and compile the Software, ...

So no, you are not allowed to distribute it. Nowhere it is said that you are allowed to distribute it, so it falls back to all rights reserved.

**Comment by SkyfallWasTaken** [comment]
I see, but imo my idea in the 2nd comment works best for both party (allowing people to distribute the jar, but keeping the no commercial clause in the license)

This is your mod though, so I respect whatever choice you do!

**Comment by tr7zw** [comment]
I mean, what is the use case to be able to distribute other people's mods?

**Comment by SkyfallWasTaken** [comment]
Honestly I don't really know, but it does feel weird, especially since people who will upload your work to some site probably won't follow the license anyway, imo it just harms people with a legit use case.

**Comment by tr7zw** [comment]
Yea, but there are no legit use cases, that's my point. 
Modpacks download from Modrinth/CurseForge. There is never a reason for people to re-upload other people's mods somewhere. I made this license to still grand some permissions so people can freely tinker with the code, could as well have gone with what many other big mods do and just use All Rights Reserved.

**Comment by SkyfallWasTaken** [comment]
I guess that makes sense, thanks for explaining!
