### ISSUE TITLE
Epic Fight Compatible

### ISSUE THREAD

**Issue by Dr-WeiAL** [tr7zw/3d-Skin-Layers#74]
Installing Skin Layers 3D and Epic Fight at the same time will cause the first-person view to see the double skin in the air and not display properly on the player model
For this he came up with a solution
https://github.com/Yesssssman/epicfightmod/issues/536
![image](https://user-images.githubusercontent.com/47446553/177009240-9782f33f-e105-4a43-9e58-bbfadf1a7703.png)
![image](https://user-images.githubusercontent.com/47446553/177009267-777f4e7f-ed1e-49f3-b049-502d39e0c6f3.png)

**Comment by tr7zw** [comment]
Not possible to make epic fight compatible.
