### ISSUE TITLE
Incompatibility with Entity Texture Features Emissive Lighting

### ISSUE THREAD

**Issue by GhostIsBeHere** [tr7zw/3d-Skin-Layers#77]
When the 3D skin layer is enabled, emissive player model textures from Entity Texture Features doesn't render. It stays dark and ignores the emissivness.

**Comment by Traben-0** [comment]
this has been resolved in ETF release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0

**Comment by GhostIsBeHere** [comment]
Wonderful!

**Comment by tr7zw** [comment]
Really cool!
