### ISSUE TITLE
Crashes in Minecraft 1.19 Forge

### ISSUE THREAD

**Issue by 1-1037** [tr7zw/3d-Skin-Layers#78]
Minecraft crashes before even getting to the main menu on the latest 1.19 Forge version, even if it is the only mod installed.

# Steps to Reproduce:
1. Install latest 1.19 forge version (41.0.98)
2. Install 3D Skin Layers
3. Launch Minecraft
4. Game crash

# Versions:
Minecraft: 1.19
3D Skin Layers: 3dskinlayers-forge-1.4.7-mc1.19
Forge: 41.0.98

Screenshot: ![image](https://user-images.githubusercontent.com/77138306/178927793-15c6f428-255b-4edb-a1c9-6dea4323c34c.png)
Crash log: [crash-2022-07-14_02.31.37-fml.txt](https://github.com/tr7zw/3d-Skin-Layers/files/9109598/crash-2022-07-14_02.31.37-fml.txt)

**Comment by tr7zw** [comment]
Known issue because Forge basically broke all mods. Downgrade to an older version for now.

**Comment by tr7zw** [comment]
Fixed with the 1.19.1 release.
