### ISSUE TITLE
1.12 Incompatible with OpenModsLib

### ISSUE THREAD

**Issue by Chronstell** [tr7zw/3d-Skin-Layers#79]
Not sure if you're still releasing updates/bug fixes for the Minecraft 1.12 version of this mod, and sorry if it isn't, but here's the issue. 

It doesn't even get to the forge mod initialization screen so I had to look at the log file to find the issue. It occurs when only this and OpenModsLib is installed. 

Here is that log file: [latest.log](https://github.com/tr7zw/3d-Skin-Layers/files/9265668/latest.log)

Interestingly, if I edit the file names so that 3d skin layers is loaded after [OpenModsLib](https://www.curseforge.com/minecraft/mc-mods/openmodslib), the game will load and even lets me into the world. The only consequence that seems to come of it is if I then install the [OpenBlocks](https://www.curseforge.com/minecraft/mc-mods/openblocks) mod and use the Hang Glider item, it doesn't pose the model so the player just stands upright through the center of the glider's model like so.
![2022-08-05_01 03 54](https://user-images.githubusercontent.com/50534961/183012676-d1dede3d-73bd-4e2e-870a-d0ded04a309f.png)

This hopefully means some sort of compatibility is possible that doesn't require janky methods of changing file names to manipulate the mod load order like I do. If not, at least I can use them together with my methods seemingly without any game breaking issues.

**Comment by tr7zw** [comment]
Don't think there is anything I can do about this. OpenMods seems to use CoreMods, which is the predecessor to Mixins. Changing the Mod name to trick forge into loading my mixins first is kind of a janky workaround that I can't really release for 1.12.
