### ISSUE TITLE
 In 1.18.2_ Error generated by dragon_head

### ISSUE THREAD

**Issue by A-LittlePig** [tr7zw/3d-Skin-Layers#84]
In my 1.18.2 world, I closed the rest of mods, once I placed dragon_ Head in the world, the world will collapse and report mistakes. After I close this mod, I can place and display dragon_ Head, what's the problem? Thank you

**Comment by tr7zw** [comment]
I need the crash report. The dragon head should have nothing to do with this mod.

**Comment by A-LittlePig** [comment]
[错误报告-2022-9-23_7.44.27.zip](https://github.com/tr7zw/3d-Skin-Layers/files/9630022/-2022-9-23_7.44.27.zip)

**Comment by tr7zw** [comment]
This is an outdated version and an issue that has been fixed a long time ago. That's 1.3.1 for 1.18.1. The latest is 1.4.6 1.18.
