### ISSUE TITLE
How can I make a skin that uses 3D layers?

### ISSUE THREAD

**Issue by Josh-65** [tr7zw/3d-Skin-Layers#89]
This mod works and I would like to make one but can't find any information to do so.

**Comment by Josh-65** [comment]
And how would i make a skin that uses layers. Is there a program or site that i can use?

**Comment by tr7zw** [comment]
Photoshop, Gimp, Paint, https://www.minecraftskins.com/skin-editor/ , https://minecraft.novaskin.me/ , https://www.minecraftskins.net/skineditor anything that can edit a picture. Worst case look up tutorials on youtube I guess.
