### ISSUE TITLE
Renamed Mob-Head Crash

### ISSUE THREAD

**Issue by Terraphice** [tr7zw/3d-Skin-Layers#90]
Crash to desktop when equipping a (renamed) zombie head on a multiplayer server. Unsure if the issue was it being renamed or not however.

[latest.log](https://github.com/tr7zw/DisguiseHeads/files/9893387/latest.log)

**Comment by tr7zw** [comment]
Ah no, I stand corrected. Just looked like it, because 3d Skin Layers triggered the bug first, but the faulty logic is indeed in DisguiseHeads.

**Comment by tr7zw** [comment]
Please test with https://github.com/tr7zw/DisguiseHeads/actions/runs/3356510484

**Comment by Terraphice** [comment]
Seems to have fixed the issue when testing with the previous renamed mob-head.

**Comment by tr7zw** [comment]
👍 , will release the fix tomorrow.
