### ISSUE TITLE
Configs don't respect custom game directory [BUG]

### ISSUE THREAD

**Issue by DevScyu** [tr7zw/3d-Skin-Layers#91]
### Describe the bug
**Expected:**
Config files to be saved into my custom game directory.
**Actual:**
Config files were saved to the `.minecraft` folder

### To Reproduce
Launch game with different game directory set in the launcher

My profile is set to `%APPDATA%/.wynntils`, however, configs are being saved to `%APPDATA%/.minecraft`
![image](https://user-images.githubusercontent.com/15234414/200563288-a07f6b49-d4e7-4677-818e-fea629b9887c.png)
![image](https://user-images.githubusercontent.com/15234414/200559259-33a3c5a6-7171-49e4-8c23-e1bff7fbcbbd.png)

### Version Information
 - OS: Tested on Mac and Windows
 - Launcher: Official Minecraft Launcher
 - Minecraft 1.18.2
 - Fabric Loader version 0.14.9
 - Mod Version 1.4.6

**Comment by tr7zw** [comment]
It uses the current directory for the config. Looks more like the launcher doesn't set that correctly. Will look into it. Which launcher is this?

**Comment by DevScyu** [comment]
Vanilla minecraft launcher

**Comment by tr7zw** [comment]
Hm, good job Mojang. Curseforge launcher does it correctly. Will have to look into how mc knows about this launcher value.

**Comment by tr7zw** [comment]
Getting resolved by Mojang, so doesn't need tracking here.
