### ISSUE TITLE
Suggestion, support with straw statues? 

### ISSUE THREAD

**Issue by SebSemos** [tr7zw/3d-Skin-Layers#92]
With [straw statues](https://www.curseforge.com/minecraft/mc-mods/straw-statues) we can get player skin by renaming an armor stand. Would be great to get the 3D on them too :)

**Comment by tr7zw** [comment]
This mod provides an API for other mods to use the 3d features. I won't add mod support to this mod(I don't have the time to make all the mobs in all the mods 3d).
