### ISSUE TITLE
Layers do not stay when using certain emotecraft emotes 1.19.2 Fabric

### ISSUE THREAD

**Issue by AnomalousDeity** [tr7zw/3d-Skin-Layers#94]
We got the dr livesey walk to do a phonk walk meme in our server. however our 2nd layers detach and do not move with the body

**Comment by Gerutro** [comment]
The same problem on 1.20.1

**Comment by tr7zw** [comment]
Hm, seems that the compatibility layer got lost during the 1.18 to 1.19 transition, will have to rebuild it.

**Comment by tr7zw** [comment]
Hm crap, could be that the compatibility got nuked by the 1.6.0 release again, in that case will have to re-add it for good this time in the next release.

**Comment by tr7zw** [comment]
Never mind, I forgot that the transform logic is implemented in the bendy-lib(which is developed by the author of emotecraft). So bestcase open an issue there with the emotes so they can look into it.
